### ISSUE TITLE
Overwriting default properties doesn't work

### ISSUE THREAD

**Issue by ermshiperete** [editorconfig/editorconfig-vscode#102]
It looks like the plugin doesn't allow to overwrite properties with more specific ones. The `.editorconfig` file below lists my settings: I want to use tab indentation for all files except for the files that VS generates. There I want to indent with 2 spaces.

```ini
# Defaults
[*]
indent_style = tab
indent_size = tab
tab_width = 4

# Settings Visual Studio uses for generated files
[*.{csproj,resx,settings,vcxproj*,vdproj,xml}]
indent_style = space
indent_size = 2
```

**Comment by jedmao** [comment]
Can you do `npm install editorconfig` and then run `editorconfig *.csproj` to see if the settings are what you expect?

**Comment by ermshiperete** [comment]
Yes, the settings this displays are correct.

I played around a bit more and eventually discovered that it's the `vscode-whitespace` extension that doesn't honour the settings. With that disabled things work like they should. Opening an issue there.
