### ISSUE TITLE
Respect global EditorConfig file

### ISSUE THREAD

**Issue by OliverJAsh** [editorconfig/editorconfig-vscode#107]
I have found that my global EditorConfig, located in my home directory, is not respected by this extension.

I do not have an EditorConfig is my project which would possibly override this.

**Comment by jedmao** [comment]
I don't believe that's a supported EditorConfig feature. Where did you get the idea that that would work in the first place?

**Comment by OliverJAsh** [comment]
I thought EditorConfig traversed directories until it found a config file with `root = true`?

**Comment by jedmao** [comment]
It does. Is the project in question also under your home directory?

**Comment by OliverJAsh** [comment]
It is indeed.

**Comment by jedmao** [comment]
And your project does not have a `root=true` in the `.editorconfig`?

**Comment by jedmao** [comment]
What happens if you `npm install editorconfig -g` and run `editorconfig the-file-in-question.js`?

**Comment by OliverJAsh** [comment]
@jedmao I do not have a local config file in my project. 

When I run that command, I see the desired preferences, but they are not respected my VSCode. `indent_size = 2` to be precise.

**Comment by jedmao** [comment]
One last idea. What happens if you create an `.editorconfig` file in your project root. Does it still not work?

**Comment by OliverJAsh** [comment]
Creating a config file in my project root does work, of course.

If I remote `root = true`, it still works because, in your example, the config for the file I'm interested in has been specified.

The use case I have is my global config file specifies `indent_size = 2` for `package.json`, but my local config does not specify anything for that file (and/or it doesn't exist).

**Comment by xuhdev** [comment]
What the path of your global file?

**Comment by OliverJAsh** [comment]
`~/.editorconfig`. My project dir is `~/dev/foo`

**Comment by jedmao** [comment]
@xuhdev he's already confirmed that running the shell command `editorconfig package.json` is returning the configuration he expects (i.e., `indent_size = 2`). What doesn't seem to make any sense here is that somehow adding an `.editorconfig` file at his project root fixes it, even though the configuration is no different.

This extension uses the exact same [`editorconfig` package from npm](https://www.npmjs.com/package/editorconfig), so I don't see how the extension could be behaving any differently than the CLI.

**Comment by OliverJAsh** [comment]
Tried exactly the same steps this morning and I can no longer reproduce, so I'll close this.

Sorry for wasting your time, I tried to be diligent filing this issue but obviously not enough.

Thanks!
