### ISSUE TITLE
this plugin only affect .js files?

### ISSUE THREAD

**Issue by zzzgit** [editorconfig/editorconfig-vscode#108]
Hello.
I found that this plugin only affect the files with `.js` extension,is it right?
How could I make it affect some other file types?

**Comment by jedmao** [comment]
It's for all file types. What makes you think it's just for js files?

**Comment by SamVerschueren** [comment]
Share your config file, it might be wrongly configured.

**Comment by jedmao** [comment]
@SamVerschueren, we've been getting a lot of issues like this, so I'm adding some issue and pull request templates in #112.

**Comment by zzzgit** [comment]
```property
root = true

[*]
end_of_line = lf
insert_final_newline = true

[*.{js,py}]
charset = utf-8
indent_style = tab
indent_size = tab
#tab_width = 4
```

**Comment by zzzgit** [comment]
yes,I just config that for `.js` and `.py` files
