### ISSUE TITLE
Any intention of merging this effort with Microsoft/vscode-editorconfig?

### ISSUE THREAD

**Issue by rhbecker** [editorconfig/editorconfig-vscode#11]
Seems like forces could join together for one super effort?

https://github.com/Microsoft/vscode-editorconfig/issues/23

**Comment by jedmao** [comment]
It's up to Microsoft. They have their hands full, for sure, but I can't wait for them to make decisions while EditorConfig becomes stale. This fork was intended to have faster iteration cycles and evolve faster. I think that's proven to work pretty well so far.

**Comment by rhbecker** [comment]
Ha - I didn't even notice this was a fork of theirs. That makes sense and seeing your intentions / reasoning helps me decide which to install, which might make that a good candidate for inclusion your readme.

It'll be interesting to see how they're thinking about it, assuming they respond (seems like they're generally pretty responsive).

**Comment by jedmao** [comment]
I did put that at the top of my readme.

**Comment by xuhdev** [comment]
Perhaps we can add an explanation of the situation in the README file? It was confusing for me why we had this fork.

**Comment by jedmao** [comment]
Done in https://github.com/editorconfig/editorconfig-vscode/commit/3f071886acf86174b4121a56d57f9ebb416cca71

**Comment by SamVerschueren** [comment]
:+1: looks good

**Comment by rhbecker** [comment]
@jedmao: sorry if my initial README suggestion was unclear - what you added here is perfect. thanks!
