### ISSUE TITLE
0.6.5 does not honor tab size settings

### ISSUE THREAD

**Issue by zgoda** [editorconfig/editorconfig-vscode#135]
### Expected behavior

Tab size settings applied to editor in workspace

### Actual behavior

Invalid tab size in editor

### Steps to reproduce the behavior

```ini
root = true

[*]
indent_style = space
indent_size = 4

[*.{c,cpp,h,hpp,proto}]
indent_style = tab
indent_size = 2
```

`indent_style` is `tab` but I still see `indent_size = 4` in editor:

![zrzut ekranu z 2017-04-10 09-30-12](https://cloud.githubusercontent.com/assets/141999/24850428/5b203780-1dd0-11e7-8b97-d99c5fb20b78.png)

**Comment by zgoda** [comment]
Moreover, for new files it does not honor neither `indent_style` nor `indent_size`, everything is indented by 4 spaces. It does not matter if the configuration is local to workspace directory or placed in one of parent dirs.

**Comment by kalinchernev** [comment]
I also feel pain about this.
In the project folder:
```
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.md]
trim_trailing_whitespace = false
```

Every file starts with 4 spaces ... (it's really annoying to be honest)

**Comment by Guillaumez** [comment]
Same problem ! I now have 4 spaces instead of 2

**Comment by jedmao** [comment]
Having issues reproducing. If someone can tell me the following:
1. **Both** your user and workspace settings for the following:
* `editor.insertSpaces`
* `editor.tabSize`
2. Your `.editorconfig` file (the whole thing).
3. The file path of the file in question.
4. What the EditorConfig output window is printing out.

**Comment by jedmao** [comment]
@zgoda by "new files" do you mean untitled documents? EditorConfig works off of the full file path, including extension, so that would make some kind of sense. That said, I just published v0.7.0 to assume untitled documents live at the workspace root. That should help at least get the default EditorConfig settings in there.

**Comment by guzart** [comment]
Updating to v0.7.0 solved this issue for me. Thank you

**Comment by jedmao** [comment]
@guzart, v0.7.0 only added a feature to apply EditorConfig to new/untitled documents. There were no specific fixes to this issue, so I'm a bit confused how that would be true.

**Comment by marcincichocki** [comment]
My config wasn't working on vs code 1.11.1 and editorconfig for vs code 0.7. I've downgraded to vs code 1.10.2 and  editorconfig for vs code 0.6.2 and everything is working again.

```
# Editor configuration, see http://editorconfig.org
root = true

[*]
charset = utf-8
indent_style = space
indent_size = 2
insert_final_newline = true
trim_trailing_whitespace = true

[*.md]
max_line_length = off
trim_trailing_whitespace = false
```

user settings:
```
{
    "typescript.check.tscVersion": false,
    "stylelint.enable": true,
    "scss.validate": false,
    "files.associations": {
        "*.vue": "vue"
    },
    "workbench.iconTheme": "vs-seti",
    "css.validate": false,
    "keyboard.dispatch": "keyCode"
}
```

**Comment by guzart** [comment]
@jedmao I mistakenly thought it fixed the issue but it doesn't, apologize for any confusion

**Comment by strothj** [comment]
I'm also experiencing the same issue as @marcincichocki. My tab setting in new and existing is not being honored. Problem started after a recent update to VSCode. I've tried removing and reinstalled the extension. I've also made sure the corresponding extension folder was removed.
I'm also using Ubuntu 16.04 and VSCode 1.11.1.
For now I've had to set the default in VSCode settings: `"editor.tabSize": 2`

**Comment by jedmao** [comment]
Is anyone experiencing this issue who is **NOT** on Linux?

**Comment by jedmao** [comment]
Still cannot reproduce on Windows 10. Here's my `.editorconfig`:

```ini
root = true

[*]
indent_style = space
indent_size = 4

[*.ts]
indent_style = tab
indent_size = 2
```
And here's what I see printed in the EditorConfig output window when I switch to `foo.ts`:

```
Applying configuration to foo.ts...
Using configuration map...
foo.ts: {"insertSpaces":false,"tabSize":2}
```
I really want to fix this ASAP, guys, but I can't repro. Nobody can provide better repro steps? Please refer to the new [`ISSUE_TEMPLATE.md`](https://github.com/editorconfig/editorconfig-vscode/blob/master/.github/ISSUE_TEMPLATE.md) for guidance.

Also, @zgoda, you realize you can set `tab_width = 2` too, right?

**Comment by ianlini** [comment]
Hi, @jedmao. In my case, there is no any output (no EditorConfig option in the output window). I think the extension totally fails to start.
I also found that there are some error messages at the developer tools:
```
[Extension Host] Activating extension `EditorConfig.EditorConfig` failed: Cannot find module './InsertFinalNewline'.
[Extension Host] Activating extension `EditorConfig.EditorConfig` failed:  Cannot find module './InsertFinalNewline'
[Extension Host] Here is the error stack:  Error: Cannot find module './InsertFinalNewline'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Function.J.i._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:374825)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/bist/.vscode/extensions/EditorConfig.editorconfig-0.7.0/out/src/transformations/index.js:2:28)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.J.i._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:374825)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/bist/.vscode/extensions/EditorConfig.editorconfig-0.7.0/out/src/DocumentWatcher.js:14:27)
    at Module._compile (module.js:556:32)
Activating extension `EditorConfig.EditorConfig` failed: Cannot find module './InsertFinalNewline'.
There was an error in running the linter 'prospector'
```

**Comment by ianlini** [comment]
I can reproduce this error with empty project.

**Comment by jedmao** [comment]
@ianlini thank you! I know exactly what's going on now. I must have done a rename on that particular file at some point and because I already had `insertFinalNewline.js` in my compiled `out/` folder, every time I ran the TypeScript compiler w/ the `tsc` command it just overwrote it w/o changing it to `InsertFinalNewline.js`. Notice the capital "I" at the beginning! I'm going to publish a patch right now.

**Comment by jedmao** [comment]
I believe it's fixed in #142, published as v0.9.1. Please, let me know if that fixes it or if y'all continue to experience issues. Such a weird bug today! Be happy to reopen the issue if it's not solved.

**Comment by ianlini** [comment]
Thank you @jedmao! v0.9.1 fixed my problem.

**Comment by JimiC** [comment]
@jedmao Case-sensitivity is a bitch when developing on Windows and targeting Unix-style OS. Maybe you should add `"forceConsistentCasingInFileNames": true` in your `tsconfig.json`.

**Comment by zgoda** [comment]
Works fine, thank you.

**Comment by jedmao** [comment]
@JimiC that wouldn't solve the problem. It's a bit hard to explain, but a long time ago in Windows history I used to have this scenario in which I would have a file, say, named `foo.js` on my file system. I hit F2 to rename the file to `Foo.js` and hit ENTER, only to find that the new case was not assigned to the file name. Nowadays, with Windows 10, this is no longer a problem, however, when running the `tsc` compiler, with a file named `foo.ts`, it creates an output file of `foo.js`, which I never cleaned up. So I rename `foo.ts` to `Foo.ts` and the next time I run `tsc` it attempts to write the new `Foo.js` file to output, but according to Windows, the file already exists. It writes the new file contents, but doesn't change the "existing" file name. I have to delete the damn file before `tsc` will output the correct case! Crazy, right?

**Comment by JimiC** [comment]
@jedmao I always use a `precompile` `npm` script with `rimraf ./outDir`. Saves the hassle.

**Comment by jedmao** [comment]
I do too, on most projects. I've never had this specific problem before though.

**Comment by jedmao** [comment]
@JimiC I just created a TypeScript issue at https://github.com/Microsoft/TypeScript/issues/15129 that might better illustrate what's going on.

**Comment by bmacnaughton** [comment]
I don't know that this is related but EditorConfig stopped working for me altogether. I believe it is when I updated to vs code 1.11.1 but am not positive.

My .editorconfig file is in the git root of the project.

```
root = true

[*]
charset = utf-8
indent_style = space
indent_size = 4
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true

[*.{js, vue, scss}]
indent_size = 2
```

There is not another .editorconfig file in that file hierarchy. I'm running on Linux and it seems as if the .editorconfig file is being ignored altogether. Is there some way to check if it is found?

**Comment by jedmao** [comment]
@bmacnaughton please file a separate issue w/ the new issue template filled in. I think that'll help the most. I need to know what extension version you have too. Really need to be thorough to fix issues like this one.

If the extension loads at all, you should be able to see changes in the EditorConfig output window. In vscode, select `View -> Output` to see the output window.
