### ISSUE TITLE
.editorconfig is picking up incorrect indentation

### ISSUE THREAD

**Issue by bmacnaughton** [editorconfig/editorconfig-vscode#145]
Please fill-in this template.

- [x] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).
- [ ] I tried running `code --disable-extensions` and the issue did **NOT** present itself.
If I disable extensions then .editorconfig won't be active and it should use default tab settings.

Delete the following condition if it doesn't apply to your case:

If the extension is not picking up the expected configuration for a file:
- [x] I tried `npm install editorconfig -g` and ran `editorconfig [file-in-question]` and the configuration was what I expected. If not, please file on the [`editorconfig-core-js` issue tracker](https://github.com/editorconfig/editorconfig-core-js/issues).

Output was:
```ini
charset=utf-8
indent_style=space
indent_size=2
end_of_line=lf
insert_final_newline=true
trim_trailing_whitespace=true
tab_width=2

```
## Issue

|             | Visual Studio Code | editorconfig-vscode |
|-------------|--------------------|---------------------|
| **Version** | `1.11.1`            | `0.9.2`             |

### Root `.editorconfig` File

```ini
root = true

[*]
charset = utf-8
indent_style = space
indent_size = 4
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true

[*.{js,vue,scss}]
indent_size = 2
```

Are there any other relevant `.editorconfig` files in your project? No

| Visual Studio Code Setting     | Default | User    | Workspace |
|--------------------------------|---------|---------|-----------|
| `editor.insertSpaces`          | `true`  | `____`  | `____`    |
| `editor.tabSize`               | `4`     | `_`     | `_`       |
| `editor.trimAutoWhitespace`    | `true`  | `____`  | `____`    |
| `files.autoSave`               | `"off"` | `"___"` | `"___"`   |
| `files.insertFinalNewline`     | `false` | `_____` | `_____`   |
| `files.trimTrailingWhitespace` | `false` | `true` | `_____`   |
| `editor.detectIndentation` | `true` | `false` | `_____` |

### File opened

`./src/components/lmd-app.vue`

### Expected behavior

```ini
indent_size = 2
```

### Actual behavior

```ini
indent_size = 4
```
Editor config is clearly loading - it's in the Output window.

Here's the log from it:

```
Initializing document watcher...
Rebuilding config map...
extension-output-#2.testOutput: Using EditorConfig core...
/home/bruce/ds/lmd/.editorconfig: Using EditorConfig core...
Detected change in configuration: {"tabSize":4,"insertSpaces":true}
/home/bruce/ds/lmd/.editorconfig: {"insertSpaces":true,"tabSize":4}
/home/bruce/ds/lmd/.editorconfig: {"insertSpaces":true,"tabSize":4}
extension-output-#2.testOutput: Applying configuration map...
extension-output-#2: {"insertSpaces":true,"tabSize":4}
/home/bruce/ds/lmd/.editorconfig: Applying configuration map...
/home/bruce/ds/lmd/.editorconfig: {"insertSpaces":true,"tabSize":4}
extension-output-#2.testOutput: Applying configuration map...
extension-output-#2: {"insertSpaces":true,"tabSize":4}
```
It just added these lines

```
/home/bruce/ds/lmd/.editorconfig: Applying configuration map...
/home/bruce/ds/lmd/.editorconfig: {"insertSpaces":true,"tabSize":4}
```

Then these
```
extension-output-#2.testOutput: Applying configuration map...
extension-output-#2: {"insertSpaces":true,"tabSize":4}
```

I don't know that it matters but I run two different instantiations of vscode both with the same directory root.

**Comment by jedmao** [comment]
@bmacnaughton are you actually opening the `lmd-app.vue` file? Because the EditorConfig output window doesn't seem to detect the opening of that file at all.

I've recreated your project structure on Windows 10 and I'm seeing the following:

```
.editorconfig: Applying configuration map...
.editorconfig: {"insertSpaces":true,"tabSize":4}
src/components/lmd-app.vue: Applying configuration map...
src/components/lmd-app.vue: {"insertSpaces":true,"tabSize":2}
```

**Comment by jedmao** [comment]
@bmacnaughton thanks so much for the details! I _think_ I found and fixed the issue, but please let me know if it's still a problem in v0.9.3.

**Comment by bmacnaughton** [comment]
> are you actually opening the lmd-app.vue file?
Well, I haven't in quite a while; it's been opened by vscode saving the state. But I have opened multiple `.vue` files that it hasn't picked up the config for.

**Comment by jedmao** [comment]
What about now? Version 0.9.3?

**Comment by bmacnaughton** [comment]
Just tried it. It seems to work now - thank you! I hadn't realized how much
I depended on this until it was gone.
