### ISSUE TITLE
File specific settings not applied

### ISSUE THREAD

**Issue by Stanzilla** [editorconfig/editorconfig-vscode#147]
Please fill-in this template.

- [x] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).
- [x] I tried running `code --disable-extensions` and the issue did **NOT** present itself.

Delete the following condition if it doesn't apply to your case:

If the extension is not picking up the expected configuration for a file:
- [x] I tried `npm install editorconfig -g` and ran `editorconfig [file-in-question]` and the configuration was what I expected. If not, please file on the [`editorconfig-core-js` issue tracker](https://github.com/editorconfig/editorconfig-core-js/issues).

## Issue

|             | Visual Studio Code | editorconfig-vscode |
|-------------|--------------------|---------------------|
| **Version** | `x.x.x`            | `x.x.x`             |
| **Version** | 1.11.2  | 0.9.3 |
### Root `.editorconfig` File

```ini
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = crlf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.md]
trim_trailing_whitespace = false

[{babelfish.lua, ForAllIndentsAndPurposes.lua}]
indent_style = space
indent_size = 4

```

Are there any other relevant `.editorconfig` files in your project? Yes / No
no

### File opened

`WeakAuras/ForAllIndentsAndPurposes.lua`

### Expected behavior

```ini
indent_size = 4
```

### Actual behavior

```ini
indent_size = 2
```

### Additional comments or steps to reproduce

If I split it and do 
```ini

[babelfish.lua]
indent_style = space
indent_size = 4

[ForAllIndentsAndPurposes.lua]
indent_style = space
indent_size = 4
```
it works.

**Comment by jedmao** [comment]
I think you just need to remove the line break in your file list. Multi-line is not supported.

**Comment by Stanzilla** [comment]
@jedmao line break? where?

**Comment by jedmao** [comment]
Oh sorry my phone displayed it wrong. Can you try removing the space between the two lua files?

**Comment by Stanzilla** [comment]
@jedmao yup, that works, too. thank you!

**Comment by jedmao** [comment]
It's not a valid bug. Also, the 3rd check box might not have been done properly.
