### ISSUE TITLE
Incorrect behavior with editor.detectIndentation option

### ISSUE THREAD

**Issue by mrmlnc** [editorconfig/editorconfig-vscode#148]
Please fill-in this template.

- [X] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).
- [X] I tried running `code --disable-extensions` and the issue did **NOT** present itself.

## Issue

|             | Visual Studio Code | editorconfig-vscode |
|-------------|--------------------|---------------------|
| **Version** | `1.11.2`            | `0.9.3`             |

### Root `.editorconfig` File

<details>

  <summary>~/.editorconfig</summary>

  ```ini
# editorconfig.org
root = true

[*]
indent_style = tab
indent_size = 4
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

# The indent size used in the `package.json` file cannot be changed
# https://github.com/npm/npm/pull/3180#issuecomment-16336516
[{.travis.yml,npm-shrinkwrap.json,package.json}]
indent_style = space
indent_size = 2
```
</details>

| Visual Studio Code Setting     | Default | User    | Workspace |
|--------------------------------|---------|---------|-----------|
| `editor.detectIndentation` | `true` | `false` | `none` |
| `editor.insertSpaces`          | `true`  | `____`  | `____`    |
| `editor.tabSize`               | `4`     | `8`     | `_`       |
| `editor.trimAutoWhitespace`    | `true`  | `____`  | `____`    |
| `files.autoSave`               | `"off"` | `"___"` | `"___"`   |
| `files.insertFinalNewline`     | `false` | `true` | `_____`   |
| `files.trimTrailingWhitespace` | `false` | `true` | `_____`   |

### File opened

`./sandbox_ctl.py`

### Expected behavior

```ini
indent_size = 8
insertSpaces = true
```

### Actual behavior

```ini
indent_size = 4
insertSpaces = false
```

### Additional comments or steps to reproduce

Cool Issue template, but very long 🌵 

> I have no workspace config, but have a global `.editorconfig` file. 

I open `settings.json` file and set `editor.detectIndentation` to `true`. It seems to me, this is correct behavior, because I have `{}` and plugin set default settings:

```log
/Users/mrmlnc/Library/Application Support/Code/User/settings.json: setEndOfLine(LF)
/Users/mrmlnc/Library/Application Support/Code/User/settings.json: editor.action.trimTrailingWhitespace
Detected change in configuration: {"tabSize":8,"insertSpaces":true}
/Users/mrmlnc/Library/Application Support/Code/User/settings.json: setEndOfLine(LF)
/Users/mrmlnc/Library/Application Support/Code/User/settings.json: editor.action.trimTrailingWhitespace
Detected change in configuration: {}
sandbox_ctl.py: Applying configuration map...
sandbox_ctl.py: {"insertSpaces":false,"tabSize":4}
```

Now I set `editor.detectIndentation` to `false`.  Plugin correct pick up my settings:

```log
/Users/mrmlnc/Library/Application Support/Code/User/settings.json: setEndOfLine(LF)
/Users/mrmlnc/Library/Application Support/Code/User/settings.json: editor.action.trimTrailingWhitespace
Detected change in configuration: {"tabSize":8,"insertSpaces":true}
```

But when I switch to `sandbox_ctl.py` file I have wrong settings:

```log
sandbox_ctl.py: Applying configuration map...
sandbox_ctl.py: {"insertSpaces":false,"tabSize":4}
```

This is correct behavior or something is wrong?

<details>
<summary>Full log</summary>

```
Initializing document watcher...
Rebuilding config map...
extension-output-#2.testOutput: Using EditorConfig core...
settings.json.json: Using EditorConfig core...
/Users/mrmlnc/Library/Application Support/Code/User/settings.json: Using EditorConfig core...
Detected change in configuration: {"tabSize":8,"insertSpaces":true}
/Users/mrmlnc/Library/Application Support/Code/User/settings.json: No configuration.
/Users/mrmlnc/Library/Application Support/Code/User/settings.json: No configuration.
/Users/mrmlnc/Library/Application Support/Code/User/settings.json: {"insertSpaces":false,"tabSize":4}
/Users/mrmlnc/Library/Application Support/Code/User/settings.json: setEndOfLine(LF)
/Users/mrmlnc/Library/Application Support/Code/User/settings.json: editor.action.trimTrailingWhitespace
Detected change in configuration: {}
sandbox_ctl.py: Using EditorConfig core...
sandbox_ctl.py: {"insertSpaces":false,"tabSize":4}
/Users/mrmlnc/Library/Application Support/Code/User/settings.json: Applying configuration map...
/Users/mrmlnc/Library/Application Support/Code/User/settings.json: {"insertSpaces":false,"tabSize":4}
/Users/mrmlnc/Library/Application Support/Code/User/settings.json: setEndOfLine(LF)
/Users/mrmlnc/Library/Application Support/Code/User/settings.json: editor.action.trimTrailingWhitespace
Detected change in configuration: {"tabSize":8,"insertSpaces":true}
sandbox_ctl.py: Applying configuration map...
sandbox_ctl.py: {"insertSpaces":false,"tabSize":4}
```

</details>

Also I make a [video (13mb)](https://gifyu.com/image/bbmx)

**Comment by jedmao** [comment]
It looks like the configuration map isn't being rebuilt when it should be, so it's loading an old configuration. Does that sound accurate?

As a temporary workaround, you can restart vscode whenever you change your configuration.

**Comment by mrmlnc** [comment]
Unfortunately restart not working:

```
Initializing document watcher...
Rebuilding config map...
extension-output-#2.testOutput: Using EditorConfig core...
butterfly/routes.py: Using EditorConfig core...
Detected change in configuration: {"tabSize":8,"insertSpaces":true} <<<<
butterfly/routes.py: No configuration.
butterfly/routes.py: {"insertSpaces":false,"tabSize":4} <<<<
```

And [video (5.2mb)](https://gifyu.com/image/bbYA)

**Comment by jedmao** [comment]
What's the output when you run:
```bash
npm install -g editorconfig && editorconfig sandbox_ctl.py
```

**Comment by jedmao** [comment]
Also, do you know why it says
```
Detected change in configuration: {"tabSize":8,"insertSpaces":true}
```
Do you have a `tabSize` of `8` defined somewhere?

**Comment by mrmlnc** [comment]
> Do you have a `tabSize` of `8` defined somewhere?

Yeap, it's my `editor.tabSize` in VS Code User Settings (`settings.json`).

Output:

```ini
indent_style=tab
indent_size=4
end_of_line=lf
charset=utf-8
trim_trailing_whitespace=true
insert_final_newline=true
tab_width=4
```

This is global config from `~/.editorconfig`. But this issue related to plugin, because when I set `editor.detectIndentation` to false, in your code I see, that we should pick up settings from Editor Settings, not from the configuration file.

**Comment by jedmao** [comment]
Ahh, I see now. Sorry. I should have read your `tabSize: 8` setting from before. Now I get what's happening though. The EditorConfig setting always trumps the editor setting, so the best way for you to dodge your editor setting is to set `tab_width = unset` and perhaps `indent_size = unset` too in your `.editorconfig` file. That way, it'll use your editor setting.

Your configuration is a bit weird, because your global `.editorconfig` file says you want both `tab_width=4` and `indent_size=4`; yet, your editor's user settings say that you want a tab size of `8`. It seems that your "global" preferences are in conflict, but the `.editorconfig` file always trumps the editor settings, because it's more local to the file (more specific to a file).

Anyway, everything here seems by design. I just think you need to fix your global preferences conflict and decide if you want a tab width of `8` or `4` to be your global default.

**Comment by jedmao** [comment]
Haven't heard any feedback in a while. Closing.
