### ISSUE TITLE
No settings working

### ISSUE THREAD

**Issue by MartinDawson** [editorconfig/editorconfig-vscode#149]
Please fill-in this template.

- [x] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).
- [] I tried running `code --disable-extensions` and the issue did **NOT** present itself.
- [x] I tried `npm install editorconfig -g` and ran `editorconfig [file-in-question]` and the configuration was what I expected. If not, please file on the [`editorconfig-core-js` issue tracker](https://github.com/editorconfig/editorconfig-core-js/issues).

## Issue

|             | Visual Studio Code | editorconfig-vscode |
|-------------|--------------------|---------------------|
| **Version** | `1.11.2`            | `0.9.3`             |

### Root `.editorconfig` File

```ini
[*]
indent_style = space
indent_sized = 2
end_of_line = 'lf'
```

Are there any other relevant `.editorconfig` files in your project? No

| Visual Studio Code Setting     | Default | User    | Workspace |
|--------------------------------|---------|---------|-----------|
| `editor.insertSpaces`          | `true`  | `____`  | `____`    |
| `editor.tabSize`               | `4`     | `_`     | `_`       |
| `editor.trimAutoWhitespace`    | `true`  | `____`  | `____`    |
| `files.autoSave`               | `"off"` | `"___"` | `"___"`   |
| `files.insertFinalNewline`     | `false` | `_____` | `_____`   |
| `files.trimTrailingWhitespace` | `false` | `_____` | `_____`   |

### File opened

`./test.js`

### Expected behavior

```ini
indent_style = space
indent_sized = 2
end_of_line = 'lf'
```

### Actual behavior

```ini
indent_style = space
indent_sized = 4
end_of_line = 'CRLF'
```

### Additional comments or steps to reproduce
Disabled all extensions. I must be missing something. Anything else I can try?

**Comment by jedmao** [comment]
Have you tried w/o quotes? `end_of_line = lf`? I've never seen anyone use quotes there.

**Comment by MartinDawson** [comment]
@jedmao just tried that. I then created a new .js file and it had CTRL line endings still so it didn't work.

**Comment by jedmao** [comment]
I also noticed you have `indent_sized` instead of `indent_size`. Please copy the following configuration:
```ini
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
```
Also, please output the result of `npm install editorconfig -g && editorconfig ./test.js`.

**Comment by MartinDawson** [comment]
`-- editorconfig@0.13.2

indent_style=space
indent_size=2
end_of_line=lf
tab_width=2

Indent_size is now correctly being applied to my files.

Line endings are still CRLF for ./test.js though

**Comment by jedmao** [comment]
The EOL setting is applied in file save, not file open, as it would mark the file as dirty. Is it still CRLF after a file save?

**Comment by MartinDawson** [comment]
@jedmao Thanks a lot. It works now, didn't realise that.
