### ISSUE TITLE
insert_final_newline = false doesn't remove final newline

### ISSUE THREAD

**Issue by febLey** [editorconfig/editorconfig-vscode#151]
Please fill-in this template.

- [x] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).
- [ ] I tried running `code --disable-extensions` and the issue did **NOT** present itself.

## Issue

|             | Visual Studio Code | editorconfig-vscode |
|-------------|--------------------|---------------------|
| **Version** | `1.12.2`            | `0.9.3`             |

### Root `.editorconfig` File

```ini
# EditorConfig is awesome: http://EditorConfig.org

# top-most EditorConfig file
root = true

# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
insert_final_newline = true
indent_style = space
indent_size = 2
trim_trailing_whitespace = true
charset = utf-8

[*.php]
insert_final_newline = false
indent_size = 4

[*.rst]
indent_style = tab
insert_final_newline = false

[*.{txt,html,atom,xml,xlf,tmpl,ts}]
insert_final_newline = false

[*.{md,markdown}]
trim_trailing_whitespace = false

```

Are there any other relevant `.editorconfig` files in your project? Yes / No

| Visual Studio Code Setting     | Default | User    | Workspace |
|--------------------------------|---------|---------|-----------|
| `editor.insertSpaces`          | `true`  | `____`  | `____`    |
| `editor.tabSize`               | `4`     | `2`     | `_`       |
| `editor.trimAutoWhitespace`    | `true`  | `____`  | `____`    |
| `files.autoSave`               | `"off"` | `"___"` | `"___"`   |
| `files.insertFinalNewline`     | `false` | `_____` | `_____`   |
| `files.trimTrailingWhitespace` | `false` | `_____` | `_____`   |

### File opened

`./Header.hmtl`

### Expected behavior

According to the editorconfig page the final newline should be removed if the insert_final_newline is set to false:

```
insert_final_newline: set to true to ensure file ends with a newline when saving and false to ensure it doesn't.
```

### Actual behavior

Files that end with a final newline keep those final newlines.

### Additional comments or steps to reproduce

I used the editorconfig extension for Atom and Sublime, both behaved like described in the expected behavior.

**Comment by cipchk** [comment]
+1

**Comment by jedmao** [comment]
You're right. I'm looking at the code and you're absolutely right.

There could be a number of edge cases to handle here and I'm afraid I'm quite busy with a newborn, but I would accept a PR if you have time to investigate.

**Comment by febLey** [comment]
I've worked on a solution for this. The code is currently a bit convoluted with all those if queries, but it seems to work for me. Someone should definitely review and test it.
