### ISSUE TITLE
Final newline is stripped by default when no .editorconfig is present

### ISSUE THREAD

**Issue by simast** [editorconfig/editorconfig-vscode#169]
Since 0.10 version this extension is now stripping final new lines on save by default even when there is no .editorconfig file present. Might be related to #166 ?

**Comment by febLey** [comment]
You are right, there's a bug in my PR. I'm working on it right now:

https://github.com/editorconfig/editorconfig-vscode/pull/166#issuecomment-327507350

**Comment by limonte** [comment]
Nasty bug, spent one hour today to figure out what's happening to my VS Code.
