### ISSUE TITLE
Do not activate eslint server for projects without eslint config files.

### ISSUE THREAD

**Issue by ravshansbox** [editorconfig/editorconfig-vscode#177]

**Comment by jedmao** [comment]
Duplicate of #52. This doesn't make sense, because the `.editorconfig` file could exist outside the project root(s). Also, you can either disable the extension for the project in question or add an `.editorconfig` file at the root(s) with `root = true`.

**Comment by ravshansbox** [comment]
I'm sorry, I've filed the issue to the wrong repository.
