### ISSUE TITLE
Generate editor.rulers workspace settings from max_line_length?

### ISSUE THREAD

**Issue by stkb** [editorconfig/editorconfig-vscode#181]
- [x] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).

Hi, this is a feature request. I've read #53, where `max_line_length` was previously looked at, and it was decided that there shouldn't be any sort of auto-wrapping based on this setting, which I agree with.

However something that was mentioned in that thread, but not further discussed, was generating equivalent `editor.rulers` settings based on the max_line_length, giving the user a visual guide in the editor, but nothing more. (Apparently this is what Atom already does.)

I've had a [request on my own extension](https://github.com/stkb/Rewrap/issues/55) (that does comment wrapping) to support max_line_length. Since that extension can already use rulers, I'm kinda hoping to kill two birds with one stone here.

**Comment by jedmao** [comment]
Generating how? I'm not sure what you're asking for here.

**Comment by stkb** [comment]
Yeah the problem with the `editor.rulers` setting, unlike the settings already supported, is that there's no 'in-memory' version, it has to exist in a settings.json file. So it would mean creating a `.vscode/settings.json` file in the open workspace, or adding the setting to an already-existing file.

Now choosing how to initiate this action is the difficult part. On the one end you could add an extra command that does it (kind of like an inverse of the existing `generateeditorconfig` command). Least intrusive but also least discoverable. On the other end is just doing it automatically when the workspace is opened, which of course means possibly adding to / modifying the user's files without asking them, but it could be hidden behind a setting.

In-between is some sort of popup asking the user, when all the right conditions are detected, but that can also be intrusive and is most involved to code.

**Comment by jedmao** [comment]
Obviously, we're going to steer away from anything intrusive, but I'm still not really understanding what it is that you want. What would this command be named and what would it do? Why would it do it? Let's ignore the intrusive scenarios and just focus on a golden path scenario.

**Comment by ChrisCrewdson** [comment]
There is a setting in Visual Studio code called "editor.rulers":
```
  // Render vertical rulers after a certain number of monospace characters. Use multiple values for multiple rulers. No rulers are drawn if array is empty
  "editor.rulers": [],
```
It would be wonderful if this plugin would populate from the editorconfig "max_line_length" to an entry in this array.

e.g., A editorconfig setting of `max_line_length = 100`
gets us a Code setting of `editor.rulers: [100]`

The "ruler" in Code is not a "hard" break but just a guideline, so it is debatable if this is the best Code interpretation of the editorconfig "max_line_length" which the wiki says "Forces hard line wrapping after the amount of characters specified", but I don't think there is a better setting in Code.

**Comment by jedmao** [comment]
@ChrisCrewdson thanks for the explanation. It makes sense now. I can't think of a graceful way of doing this and I think it would require way more engineering than it's worth. Also, it might be confusing that EditorConfig is somehow drawing a relationship between two completely different settings. I think there's more bad than good that can come out of this.

I think what you all really want is https://github.com/editorconfig/editorconfig/issues/89 to be implemented, in which case, the `editor.rulers` setting wouldn't even be needed. Let's continue that conversation rather than going down this rabbit hole.

**Comment by jedmao** [comment]
@stkb @ChrisCrewdson @sturlath @mloskot we need 4 more 👍 votes at https://github.com/microsoft/vscode/issues/111251 to get this feature approved for vscode. It's not exactly what you're requesting, but it's a step forward.

**Comment by mloskot** [comment]
Done @jedmao

**Comment by robsonsobral** [comment]
20!

**Comment by andrewvaughan** [comment]
In lieu of this feature, maybe the plugin can provide its own column marker for `max_line_length` with an option in the extension settings to disable it? I'm sure some implementation concepts could be brought in from [Indenticator](https://marketplace.visualstudio.com/items?itemName=SirTori.indenticator) or something to make the visual?
