### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by jminer** [editorconfig/editorconfig-vscode#182]
If it isn't too much trouble, could a new version of the extension be released to the VS Code marketplace? I think #47 being fixed is the only change, but it has been fixed for a couple months now, and I assume a number of people would like the fix to be released. (It is currently the only issue I have with the extension.) Sorry if I shouldn't be opening an issue to ask this.

**Comment by jedmao** [comment]
I just released v0.12.0, but I'm not sure if it's going to fix your issues.

**Comment by jminer** [comment]
I tested the new version and it fixed that issue. Thank you!
