### ISSUE TITLE
Not working on languages without formatter when formatOnSave is enabled

### ISSUE THREAD

**Issue by uu1t** [editorconfig/editorconfig-vscode#183]
- [x] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).
- [x] I tried running `code --disable-extensions` and the issue did **NOT** present itself.

## Issue

|             | Visual Studio Code | editorconfig-vscode |
|-------------|--------------------|---------------------|
| **Version** | `1.19.2`            | `0.11.1`             |

### Root `.editorconfig` File

```ini
root = true

[*]
insert_final_newline = true
trim_trailing_whitespace = true
```

Are there any other relevant `.editorconfig` files in your project? No

| Visual Studio Code Setting     | Default | User    | Workspace |
|--------------------------------|---------|---------|-----------|
| `editor.formatOnSave`          | `false`  | `true`  |    |

Other settings are left with default values.

### Steps to reproduce
1. Open the file whose language has no formatter such as shellscript.
2. Modify and save it.
3. `insert_final_newline` and `trim_trailing_whitespace` should work but don't.

When `editor.formatOnSave` is set to `false`, it works as expected.

**Comment by jedmao** [comment]
Looks like a vscode issue, for which I've [filed a ticket](https://github.com/Microsoft/vscode/issues/42013).

**Comment by CHQ-synaix** [comment]
This happened today in my case for .groovy files

**Comment by jedmao** [comment]
This appears to be fixed in recent versions of vscode. Willing to reopen if people still experience it.
