### ISSUE TITLE
Syntax

### ISSUE THREAD

**Issue by mighty-pirate** [editorconfig/editorconfig-vscode#184]
I am currently in the process creating a PR to add a syntax property as per https://github.com/editorconfig/editorconfig/issues/190

The idea is that a comma delimited string can be set to allow for the different language identifiers in different editors.

`syntax = cpp14,cpp`

The reasons for using a comma separated list are firstly, so there is a fallback if a syntax type cannot be found, and secondly for when syntax identifiers are different in different editors.  

A good use case for this is C/C++ header files. When using .h for both, editors will decide the syntax based on the order of loaded plugins. If I have a plugin that associated .h files with C++14, then any C header file will have the wrong syntax set. I accept that I could use .hpp for C++ headers but not everyone is doing this, so the problem still exists. I can also set file associations in the editor settings, but this is tedious to change when switching projects.

One issue I have encountered, is that when you specify a language for `[*]`, this will also change the .editorconfig syntax. Should I explicitly stop .editorconfig syntax from being modified or just accept that this would be expected behaviour based on the globbing pattern?

**Comment by ffes** [comment]
First of all, core EditorConfig doesn't have a `syntax` property.

And as you can see in https://github.com/Microsoft/vscode/issues/1800 there is no way for a plugin to set the language through an API endpoint.

**Comment by mighty-pirate** [comment]
It doesn't currently. Lets hope that it does soon.

Oh dear, I wasn't aware of that. I'll have to fork vscode first and expose or create a method that allows the syntax to be changed.

I fear I will be using these changes locally by myself though, rather than them being merged.

Thanks 👍

**Comment by jedmao** [comment]
Closing for now.
