### ISSUE TITLE
Running the contributed command:'EditorConfig.generate' failed.

### ISSUE THREAD

**Issue by peterblazejewicz** [editorconfig/editorconfig-vscode#187]
Hello
## Issue

|             | Visual Studio Code | editorconfig-vscode |
|-------------|--------------------|---------------------|
| **Version** | `Version 1.21.0-insider (1.21.0-insider)`            | `0.12.0`             |
| **Version** | `Version 1.20.1 (1.20.1)`            | `0.12.0`             |

I cannot use 'Generate .editorconfig' command in projects. It does work no more.
It outputs no errors and I can see standard error handler only:
```text
Running the contributed command:'EditorConfig.generate' failed.
```

**ADDED**
I've also found that running the generate command on the project with existing `.editorconfig` shows the same error, instead one of already existing config file

This happens on Mac OS (10.13.3 (17D47))

Thanks!

**Comment by jedmao** [comment]
Did you run the command from the command palette or from the context menu in the file explorer panel?

**Comment by peterblazejewicz** [comment]
Hi,
From command palette, I barely use mouse to focus panels. I've noticed that file panel loses focus when the command menu is active.
Yes, it works when executed via context menu in focused file panel. Thanks for pointing this out.

**Comment by jedmao** [comment]
From my understanding, ever since root workspaces were introduced, it's only currently works via the context menu. Otherwise, how do I know I'm which root to place your .editorconfig file?

**Comment by peterblazejewicz** [comment]
Very interesting indeed, because I'm using it way before a workspaces were introduced as there is no other way n VSCode to scaffold the .editorconfig.
Bear with me - I'll download the repo and try myself. 
Thanks!

**Comment by peterblazejewicz** [comment]
And I specifically wrote: I barely use mouse, that's not VStudio)

**Comment by jedmao** [comment]
Yes, the feature definitely worked before multi-root workspaces were introduced, but it had to be changed after the fact because of a certain variable we were accessing that is now deprecated.

**Comment by peterblazejewicz** [comment]
It seems that URI comes as undefined, that's the problem. I've refactored the lookup path to fallback to workspace root.
#188 
Thanks!
