### ISSUE TITLE
editorconfig-vscode causes abnormal diff information

### ISSUE THREAD

**Issue by hua03** [editorconfig/editorconfig-vscode#191]
Please fill-in this template.

- [x] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).
- [x] I tried running `code --disable-extensions` and the issue did **NOT** present itself.

## Issue

|             | Visual Studio Code | editorconfig-vscode |
|-------------|--------------------|---------------------|
| **Version** | `1.23.0`            | `0.12.1`             |

### Root `.editorconfig` File

```ini
root = true

[*]
charset = utf-8
indent_style = space
indent_size = 2
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true
```

Are there any other relevant `.editorconfig` files in your project? Yes 

## Show the bug

This file has not been modified, but it has been added to index.

![](http://opd59bmxu.bkt.clouddn.com/201818041314-K.png)

And on Github:

![](http://opd59bmxu.bkt.clouddn.com/201818041316-9.png)

## Reproduce

1. Clone a web project
2. Open the project by vscode
3. Disable all extensions except editorconfig-vscode
4. Comment  all user configurations, paste the follow configuration to user configurations.
```
{
  "editor.formatOnSave": true,
}
```
5.  Open JS file in this project
6. Format the file and observe git information. (**Note: This step may take several tries**)

**Comment by jedmao** [comment]
It was newlines, right?

**Comment by hua03** [comment]
Sorry. Now, it‘s right. My environment may be wrong then.
