### ISSUE TITLE
Getting multi-root ready

### ISSUE THREAD

**Issue by jmarandet** [editorconfig/editorconfig-vscode#192]
I have VSCode 1.21.1 and I can see the following warning in my development console : 

[EditorConfig.EditorConfig] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for 'files.trimTrailingWhitespace', provide the URI of a resource or 'null' for any resource.

=> cf. https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs#run-time-diagnostics

**Comment by jedmao** [comment]
Would you be willing to submit a PR?

**Comment by KamasamaK** [comment]
Passing `null` as a second parameter [here](https://github.com/editorconfig/editorconfig-vscode/blob/a7d8304df3fefd6bf1da9eed716d97e814efedde/src/transformations/TrimTrailingWhitespace.ts#L23) will resolve the issue quickly. Although, you would ideally want to use the resource URI, but the extension doesn't seem designed for that currently.
