### ISSUE TITLE
Editor config ignores my settings and force spaces instead of tabs

### ISSUE THREAD

**Issue by ellipticaldoor** [editorconfig/editorconfig-vscode#199]
## Issue
When I install this plugin when I try to create a new file or go to a an existing one the editor defaults into spaces and when disabled tabs work again. This is very annoying 😅

|             | Visual Studio Code | editorconfig-vscode |
|-------------|--------------------|---------------------|
| **Version** | `1.24.1`            | `0.12.4`             |

### Root `.editorconfig` File

```ini
# http://editorconfig.org
root = true

[*]
indent_style = tabs
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
```

### File opened

`./foo.js`

### Expected behavior

```ini
indent_style = tabs
```

### Actual behavior

```ini
indent_style = spaces
```

**Comment by jedmao** [comment]
What do you get if you run the CLI command `editorconfig foo.js`?

**Comment by ellipticaldoor** [comment]
I get this
```
indent_style=tabs
end_of_line=lf
charset=utf-8
trim_trailing_whitespace=true
insert_final_newline=true
```

**Comment by jedmao** [comment]
Your values are incorrect. Should be `tab` and `space`.
