### ISSUE TITLE
Invoke `trimTrailingWhitespace` before `insertFinalNewline`

### ISSUE THREAD

**Issue by SamVerschueren** [editorconfig/editorconfig-vscode#2]
If the last line in your file only has one space, it will add an extra new empty line because `insertFinalNewlineTransform` and `trimTrailingWhitespaceTransform` aren't waiting for each other because of [this](https://github.com/editorconfig/editorconfig-vscode/blob/master/src/editorConfigMain.ts#L168-L169).

#### Option 1

When #1 lands, we are able to refactor those two lines to something like this.

```js
trimTrailingWhitespaceTransform(editorconfig, editor, textDocument)
    .then(() => insertFinalNewlineTransform(editorconfig, editor, textDocument));
```

#### Option 2

Or we can change [this](https://github.com/editorconfig/editorconfig-vscode/blob/master/src/editorConfigMain.ts#L184-L187) block to

```js
if(lastLine.isEmptyOrWhitespace) {
    return;
}
```

Which will do nothing and the last space gets trimmed by the `trimTrailingWhitespaceTransform` method.

#### But...

The second option might not be a good idea though. What if `trim_trailing_whitespace` is set to `false` for a file and the last line of the file consists of one or more spaces? This means the last line is not (really) empty but it will keep those spaces in the last line. So then it might be a good idea to add another empty line. Not quite sure what the expected behaviour is for such use case.

**Comment by jedmao** [comment]
Option 1 definitely sounds like the right way to handle this.
