### ISSUE TITLE
Your extension has been featured!

### ISSUE THREAD

**Issue by auchenberg** [editorconfig/editorconfig-vscode#205]
Hi,

It's Kenneth from VS Code. I'm reaching out to tell you that we have featured your awesome VS Code extension on our marketplace https://marketplace.visualstudio.com/#VSCode.

Please work with your community to resolve any major issues, as you'll probably see a significant bump in new users trying your extension.

Thanks for the great work, and happy coding!

/k

Kenneth Auchenberg
Visual Studio Code
Program Manager, Microsoft

**Comment by xuhdev** [comment]
Awesome, that's great news! @treyhunner Can you tweet about this? I don't seem to be able to log into the Twitter account.

**Comment by ffes** [comment]
Indeed great news!

Or maybe even write a blog post about it :wink:

**Comment by ericnewton76** [comment]
Congrats.  

Seems funny for an extension that started out as code written by MS people as a VSCode extension to test its API, to later get featured... but I digress.

(Frankly I thought this was bundled up as part of VSCode?)  

If anything it should definitely be on a "Must Have" list of VSCode extensions.

**Comment by jedmao** [comment]
Agreed. EditorConfig features should ideally be built into any editor in order for it to work more effectively; however, vscode does have the nice feature of allowing us to suggest plugins for a particular workspace. The issue there is that many people are against committing editor-specific anything to a codebase.

**Comment by ericnewton76** [comment]
"many people are against committing editor-specific anything to a codebase"

Wow really?  So they'll have a specific formatting in a codebase that they wanna keep a certain way, they don't wanna specify it in the codebase?  Laughable logic!

This project works well as a separate project, I dislike how big brother Visual Studio prepackages effectively a bunch of extensions, and dont ever update them (at least prior to 2017 version, they seem better at it now)

**Comment by jedmao** [comment]
@auchenberg the worst issues with this extension today are related to vscode API limitations, which I've covered in a new vscode issue: https://github.com/Microsoft/vscode/issues/65663

Please help us move forward with a solution. Thanks!

**Comment by ericnewton76** [comment]
@jedmao Doesnt the .vscode folder have a lot of other user specific stuff in it?  

User specific stuff shouldnt be in the source repo.  A template of options could be checked in, with a readme that says "if you like my defaults, copy that tempate file."  

Project specific stuff, like editorconfig, definitely should be.  Linter settings, etc should be too.

The partition is project level vs user level.  I believe those other items mentioned dont properly partition their project settings from user preferences.

Maybe we should bring this up as issue in VSCode... lol
