### ISSUE TITLE
Extension applies (default?) settings when .editorconfig is not present

### ISSUE THREAD

**Issue by ezolenko** [editorconfig/editorconfig-vscode#207]
Please fill-in this template.

- [x] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).
- [x] I tried running `code --disable-extensions` and the issue did **NOT** present itself.

## Issue

|             | Visual Studio Code | editorconfig-vscode |
|-------------|--------------------|---------------------|
| **Version** | `1.30.0`  "user setup"         | `0.12.5`             |

### Root `.editorconfig` File
There is no `.editorconfig` in the workspace at all.

Are there any other relevant `.editorconfig` files in your project? **No**

### File opened

Python or sh files, any text file I think.

### Expected behavior

No behavior at all, since there is no config file.

### Actual behavior

Line endings are changed to CRLF, regardless of VSCode settings

### Additional comments or steps to reproduce

In workspace without editorconfig, on save (autosave is enabled), line endings are changed to CRLF, regardless of VSCode setting and regardless of original line endings in the file.

This is on Windows 10

**Comment by ezolenko** [comment]
No, no config files all the way to the root of the drive. I also checked home directory and few other places. Some projects in the same root folder might have config files.

**Comment by ezolenko** [comment]
And yeah, turning off extension fixes the problem, turning it back on brings it back

**Comment by jedmao** [comment]
You've deleted some pretty relevant sections of the issue template that would be useful in this issue. I'm afraid I am unable to reproduce on Windows 10 on a project I have, after deleting the .editorconfig file entirely.

I need to know exactly the filename of the file that is doing this. If it were `foo.ext` you need to `npm install -g editorconfig && editorconfig foo.ext` to see what the core thinks should be set on this file.

Additionally, you'll find the EditorConfig output window might be helpful in telling you what it's doing vs. what you expect.

**Comment by ezolenko** [comment]
Indeed, editorconfig does show the setting and I found the file with that setting in one of root paths :/. Sorry for bogus report.
