### ISSUE TITLE
Remove from context menu

### ISSUE THREAD

**Issue by notiv-nt** [editorconfig/editorconfig-vscode#212]
Is it possible to remove an item from the menu?

![image](https://user-images.githubusercontent.com/10743009/50889584-639cea80-1409-11e9-8cec-0b35139e1bd9.png)

## Issue

|             | Visual Studio Code | editorconfig-vscode |
|-------------|--------------------|---------------------|
| **Version** | `1.30.2 `            | `0.12.6`             |

**Comment by jedmao** [comment]
Why?

**Comment by notiv-nt** [comment]
useless. I created this file last time 2 years ago. Just copying always the same thing.

**Comment by jedmao** [comment]
Well the only way to remove it is to uninstall the extension.

**Comment by xuhdev** [comment]
Does the extension offer any other features?

**Comment by xuhdev** [comment]
Oops, I thought the screenshot is for some file manager... To be honest, I also feel a bit strange if it shows up in a context menu. I would expect it in some other menus since this item is unlikely to be frequently clicked on...

**Comment by jedmao** [comment]
It also shows up in the command palette, but it's not uncommon for an app to have multiple ways of doing the same thing. I didn't really care for the feature when it was first introduced, but I do create a lot of projects and I found myself using it multiple times. I'm not understanding why it's annoying?

**Comment by notiv-nt** [comment]
Well, just wanted to ask if there is such an opportunity

Close ? @jedmao

**Comment by jedmao** [comment]
Yeah. I think we should close. Thanks.

**Comment by tobico** [comment]
I'd also like to ask for this to be removed from the context menu. It shows up as the last item where delete would usually be, and only on folders but not on files. This has caused me to often select it by mistake when intending to delete a folder.

**Comment by jedmao** [comment]
Perhaps there’s a way to make it not the last item in the menu instead of totally removing it.

**Comment by Skulaurun** [comment]
Why not add another checkbox to options for disabling "Generate .editorconfig" from the context menu? In my opinion this is something that should be configurable.
