### ISSUE TITLE
.editorconfig changes made from outside vscode aren't picked up even when file is reopened

### ISSUE THREAD

**Issue by godmar** [editorconfig/editorconfig-vscode#214]
Please fill-in this template.

- [X] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).

### File opened

any

### Expected behavior

Not sure what to expect since I couldn't find documentation.

### Actual behavior

When I change a setting in .editorconfig with vi, it will be reflected in vscode for files that were already opened under the old settings only after a complete restart.  Specifically, if I open index.js the current settings of .editorconfig will be applied.  If I close index.js, then change .editorconfig from outside vscode, and then reopen index.js, the new settings are not applied.  If I close vscode and reopen it, the new settings are applied. The new settings are also applied immediately if I edit .editorconfig from inside vscode.

This means that if one has files opened and then creates an .editorconfig from outside vscode (for instance, by running git pull or the like), applying those settings to files that were opened in the current vscode session is not possible.

### Additional comments or steps to reproduce

Would it be possible to document the steps to apply changes to .editorconfig.
It's very confusing that if you change the .editorconfig file (from outside vscode!), then close and reopen the file in vscode, the new settings are not applied. I'm new to editorconfig and at first believed that editorconfig wasn't working.

**Comment by jedmao** [comment]
Thanks for the write-up. I don't think there's anything to document, because it looks like what you're experiencing is a bug. If it were fixed, would it still need documentation?

Also, did you know there's an EditorConfig output window in vscode that logs things as they happen? It sounds like the settings are being cached too aggressively and that needs to be reevaluated.

**Comment by godmar** [comment]
Ok. Let me add one possibly relevant piece of information. This behavior was observed when vscode was run natively on Windows 10, but the file .editorconfig was changed from within [WSL](https://docs.microsoft.com/en-us/windows/wsl/faq) in a DrvFS mounted file system (e.g. /mnt/c/Users/me/path/.editorconfig). I'm mentioning this in case the plug-in relies on any OS-level file notification facility, which WSL may or may not properly emulate. OTOH, this appears to be a setup MSFT would probably be intending to support especially since you can't have native tools like vscode access files inside the WSL emulated filesystem.

**Comment by jedmao** [comment]
@godmar that's definitely a possibility. Can you do me a favor and record your EditorConfig output window during an isolated change so we can read the output together for more insights?

Or try to reproduce outside of a WSL environment via VI or VIM or even Notepad?

**Comment by godmar** [comment]
Ok. The good news is it behaves the same on a native Linux Ubuntu, so it's not (necessarily) specific to WSL. When I reopen a file after I changed .editorconfig from outside vscode, I see:

```
..../myfile.js: Applying configuration map...
.../myfiles.js: {"insertSpaces":true,"tabSize":4}
```

where 'tabSize':4 is stale because I had just changed indent_size to 2:
```
[*]
indent_style = space
indent_size = 2
```
in my .editorconfig.

(Side question: my editorconfig actually also has other things, such as end_of_line, chart, etc., but those are not listed (?) maybe because they do not constitute overrides of defaults (?))

On the other hand, if I change .editorconfig from inside vscode, I see messages such as
```
.editorconfig file saved.
Rebuilding config map....
...../myfile.js: Using EditorConfig core ....
```

BTW, looking briefly at where this [message is coming from](https://github.com/editorconfig/editorconfig-vscode/blob/0199ff82a8573b781e2f2adb04b5eb1288372c07/src/DocumentWatcher.ts#L116-L122) I don't see at all where you'd be listening for file changes from the OS.

**Comment by jedmao** [comment]
Hey @godmar. 👋  Thanks again for your excellent write-up in filing this issue.

This whole concept of the config map goes back to the old days when Microsoft initialized this extension. It was a noble goal to cache the configuration settings, but it really doesn't work with the way that EditorConfig is supposed to work, as you've well noticed.

In my testing, the config map was really no faster than a new EditorConfig core look-up, so I went ahead and removed the whole config map thing entirely and published a new version of EditorConfig@0.12.7.

I also added a listener to the window focus event to ensure that whenever you switch apps and come back to vscode it will refresh your EditorConfig settings. This will definitely hit the hard drive more than the previous implementation, but there's really no way around it if we don't want to run into stale configs like you've been seeing.

Let's all give it a shot and see if it presents new problems or not. I'm optimistic that it will only improve peoples' experience.

Gave a great night! 🌙

**Comment by godmar** [comment]
One of the reasons for my filing this request was that the normative behavior was not documented. I wonder if adding a description to the "Details" tab in the extension install dialog would help?

Side note: I now have 0.12.7 installed, and "check for updates" shows "All extensions are up to date".  Yet, the "ChangeLog" tab does not contain an entry for 0.12.7, it ends with 0.12.6.

**Comment by jedmao** [comment]
I'm not sure what normative behavior is. How would you write this portion and is it still relevant with the fixes?

I must have forgotten to update the changelog. I'll fix later.

**Comment by godmar** [comment]
By normative behavior I meant a 1 sentence concise description of how it's supposed to work, for example: "Changes to .editorconfig become active when ..." and then complete the sentence.
