### ISSUE TITLE
Version 0.12.7 published without updating CHANGELOG.md

### ISSUE THREAD

**Issue by vovkasm** [editorconfig/editorconfig-vscode#216]
It is very important to be informed of what actually changed in extensions for editors, because of all that bad cases when hackers broke infra and publish malicious code. So when I'm not found latests changes clearly described, I waste a lot of time to study git logs to ensure that nothing bad happens after upgrade.

**Comment by ffes** [comment]
Even when a changelog is updated your can't be sure that  the infra hasn't been taken over. An updated changelog doesn't guarantee anything. A malicious commit can sneak through is somebody really wants to. If you are that suspicious you will always need to go through all the commits of every update you install to any kind of software.

**Comment by vovkasm** [comment]
@ffes Yes, in strict sense. But if changelog accurate and representative, it more probability that it is created by author of software. And it creates enough confidence to not go to commit log and diffs in most cases.
