### ISSUE TITLE
how to generate .editorconfig?

### ISSUE THREAD

**Issue by hobbsd** [editorconfig/editorconfig-vscode#220]
- [X ] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).

|             | Visual Studio Code | editorconfig-vscode |
|-------------|--------------------|---------------------|
| **Version** | `1.30.2`            | `0.12.8`             |

It took me a while to find out how to run the "generate .editorconfig" command (which I saw mentioned in the changelog), as it doesn't appear in the command palette. I found in a closed issue the reason for it not being in the command palette and that it's in the Explorer context menu. Would you consider having this handy feature mentioned in the `README`?

**Comment by jedmao** [comment]
Yes, PR welcome if you want to author it.

**Comment by hobbsd** [comment]
Thanks, I'll do that.
