### ISSUE TITLE
What is the difference between the github source code and the plug-ins downloaded from the plugin market?

### ISSUE THREAD

**Issue by developers-youcong** [editorconfig/editorconfig-vscode#224]
What is the difference between the github source code and the plug-ins downloaded from the plugin market?

What if I packaged the source code for the plugin downloaded from github into the plugin market?

**Comment by jedmao** [comment]
The code is the same as the published extension; though, I'm not sure what Microsoft is doing with it in transport. Why are you asking this question anyway? And why is it asked in this repo? Wouldn't the answer be the same for all vscode extensions; thus, better suited for the vscode issue tracker?

**Comment by developers-youcong** [comment]
Thank you for your answer
