### ISSUE TITLE
.NET coding convention settings for EditorConfig

### ISSUE THREAD

**Issue by AnthonyMastrean** [editorconfig/editorconfig-vscode#226]
- [x] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).
- [ ] I tried running `code --disable-extensions` and the issue did **NOT** present itself.

## Issue

Is there any chance that this extension could be _extended_ to support the [.NET coding conventions](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017) that Visual Studio 2017 supports? I'm not even sure if the extension is the right place for this request (as compared to some kind of new built in feature of Visual Studio Code or an extension to the OmniSharp service).

**Comment by AnthonyMastrean** [comment]
Actually, [this comment](https://github.com/OmniSharp/omnisharp-vscode/issues/2332#issuecomment-391006122) indicates that editorconfig support will get into Visual Studio Code by way of OmniSharp.

**Comment by jedmao** [comment]
Yeah this seems out of scope to this particular project. Would have to be a separate extension. Looks like they're already working on it.
