### ISSUE TITLE
Templates for specific language

### ISSUE THREAD

**Issue by saileshkush95** [editorconfig/editorconfig-vscode#230]
Please add the features for auto generating templates for specific workflow, Like for Django, Laravel and many fore

**Comment by jedmao** [comment]
Be awesome if we could get this working with GitHub too when you create a new repo.

**Comment by jedmao** [comment]
I think this is a good request for all editors though. Not just vscode.

**Comment by ffes** [comment]
Isn't https://github.com/editorconfig/editorconfig-defaults what @saileshkush95  is looking for?

Note that development in that repo is moving at a very slow pace ATM

**Comment by jedmao** [comment]
Right, I forgot about that!
