### ISSUE TITLE
How to interpret log file entry?

### ISSUE THREAD

**Issue by rowild** [editorconfig/editorconfig-vscode#232]
The prepared questions are not related to the issue I am going to ask.

Visual Studio Code: 1.34.0
editorconfig-vscode: 0.13.0
Are there any other relevant `.editorconfig` files in your project? No

-------------------------

In the log files of VS Code under `/Users/[user]/Library/Application Support/Code/logs/` I searched all entries for `globalsStorage` and found 3 altogether, which look like this:

`/Users/[user]/Library/Application Support/Code/User/globalStorage/alefragnani.project-manager/projects.json: {}`

in files named

`/Users/[user]/Library/Application Support/Code/logs/20190530T085317/exthost1/output_logging_20190530T085321/2-EditorConfig.log`

The log folders, named by date, exist from April 29 to June 3rd. All these 3 entries were found in 2 of the 3 existing `20190530[...]` folders.

My questions:
- Was there anything special going on on May 30th in the morning?
- Why does editorconfig touch `project.json`? It is not a file that the user opens, but the ProjectManager extension puts there.
- How can the entry `[...]/projects.json: {}` be interpreted? What do the curly braces mean? Does it mean that the file is deleted? Or rewritten?

The reason for the questions is:
A bunch  of people found out that all their saved projects in the ProjectManager extension were suddenly lost. After comparing dates and installed extension, we found out that this all happened to us on May 30th and that only ProjectManager and EditorConfig are the common extensions we have installed.
The thread can be found here: https://github.com/alefragnani/vscode-project-manager/issues/277

Not knowing what really caused that problem, we do our best to find out what the reason(s) could be.
Thank you for your cooperation!

**Comment by jedmao** [comment]
1. The last EditorConfig extension code change was on Feb 14.
1. The EditorConfig extension only applies to files that are opened. It doesn't know anything about project files.
1. I suspect the issue is with Project manager.

**Comment by rowild** [comment]
Thank you! -  But which app is creating log file with the name "2-EditorConfig.log" then? And what do the curly braces in the line with "[...]/projects.json: {}" mean?

**Comment by jedmao** [comment]
I don't know. Has nothing to do with this extension though. No logs are created. The output window is where the logs are printed.

**Comment by rowild** [comment]
In editorconfig, there is a DocumentWatcher class that creates logs...
