### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by vandycarlos** [editorconfig/editorconfig-vscode#233]
- Issue Type: `Performance`
- Extension Name: `EditorConfig`
- Extension Version: `0.13.0`
- OS Version: `Linux x64 5.0.0-16-generic`
- VSCode version: `1.35.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/carlos/EditorConfig.EditorConfig-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jedmao** [comment]
It seems obvious to me why this extension would cause high CPU load, but only when you switch tabs. Is there something more specific about this extension that you can explain is unacceptable?

**Comment by jedmao** [comment]
Closing, as author has not followed up on the conversation.
