### ISSUE TITLE
VSCode's language specific settings ignored

### ISSUE THREAD

**Issue by DavidArchibald** [editorconfig/editorconfig-vscode#234]
Please fill-in this template.

- [x] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).
- [x] I tried running `code --disable-extensions` and the issue did **NOT** present itself.

Delete the following condition if it doesn't apply to your case:

If the extension is not picking up the expected configuration for a file:
- [x] I tried `npm install editorconfig -g` and ran `editorconfig [file-in-question]` and the configuration was what I expected. If not, please file on the [`editorconfig-core-js` issue tracker](https://github.com/editorconfig/editorconfig-core-js/issues).

Running this just gave me nothing, as to be expected because there is no `.editorconfig`. However it does seem to find some configuration, whether from settings or from weird defaults, I don't know.

## Issue

|             | Visual Studio Code | editorconfig-vscode |
|-------------|--------------------|---------------------|
| **Version** | `1.36.1`            | `0.13.0`             |

### Root `.editorconfig` File

Nonexistent

Are there any other relevant `.editorconfig` files in your project? No

| Visual Studio Code Setting     | Default | User    | Javascript |
|--------------------------------|---------|---------|-----------|
| `editor.insertSpaces`          | `true`  | `true`  | `true`    |
| `editor.tabSize`               | `4`     | `4`     | `2`       |
| `editor.trimAutoWhitespace`    | `true`  | `true`  | `true`    |
| `files.autoSave`               | `"off"` | `"on"` | `"on"`   |
| `files.insertFinalNewline`     | `false` | `true` | `true`   |
| `files.trimTrailingWhitespace` | `false` | `true` | `true`   |

The relevant setting I've run into is `editor.tabSize`.

### File opened

Any

### Expected behavior

```ini
indent_size = 2
```

### Actual behavior

```ini
indent_size = 4
```

### Additional comments or steps to reproduce

It'll give output like:

```
[currentfile]: {"tabSize":4}
```

This leads me to believe the settings ignore language specific settings. I do not *think* that this is intended, sorry if that assumption is incorrect. This happens most minimally with the following settings:

```jsonc
{
 "[javascript]": { // Or javascriptreact and whatever else I tested.
   "editor.tabSize": 2,
  },
  "editor.tabSize": 4,
  //"editor.detectIndentation": false, # Ultimately not relevant.
}
```

This is especially odd to me because no `.editorconfig` file is required, or even an empty editor config file with `root=true` to prevent traversing up further. I would think that the extension should be no-op in a scenario like this, but it does not appear to be.

Here is a recording of an example scenario, switching from a markdown file to a `.js`(react file type) file with these settings:

![Spaces abruptly changing from 2 to 4 in a Javascript react file.](https://user-images.githubusercontent.com/19630496/61738594-80629500-ad3f-11e9-8c5a-bc11f146d7a4.gif)

(sorry if the quality isn't good)

**Comment by jedmao** [comment]
You're right. This looks like a bug. I don't personally have any bandwidth to fix it right now, but I am accepting PRs.

**Comment by bm-stschneider** [comment]
btw the error also occurs if no .editorconfig file is present

**Comment by jedmao** [comment]
I published a fix in v0.14.1, so let me know if the issue still presents itself.

**Comment by SharakPL** [comment]
@jedmao I have v0.14.4 installed currently and it's still present. Even without .editorconfig file extension itself (when it's enabled) causes problems. If I have .editorconfig like this:
````
root = true

[*]
indent_size = 2
indent_style = space
````
then the output from console command `editorconfig main.js` is:
````
indent_size=2
indent_style=space
tab_width=2
````
and in VSCode _Output_ panel for EditorConfig shows `main.js: {"insertSpaces":true,"tabSize":2}` so all good. But if I leave only `root = true` in .editorconfig, then console command has no output (as it should be, since there's no config for it), but VSCode _Output_ panel shows `main.js: {"tabSize":4}`. Basicaly it uses value of VSCode's global setting `editor.tabSize` and completely ignores language specific settings. I think all languages are affected.

Other weird thing about it is only tabSize is forced to match global setting. With VSCode config like this:
```
"editor.insertSpaces": true,
"[javascript]": {
        "editor.tabSize": 2,
        "editor.insertSpaces": false,
}
````
indentations are changed to tabs instead of spaces in .js files.

I'm using Windows 10 and VSCode 1.41.1 (user setup)

**Comment by jedmao** [comment]
Thanks for the thorough report! I am contractually unable to submit PRs to open source projects, so someone else will have to fix it.
