### ISSUE TITLE
Remove statusbar message

### ISSUE THREAD

**Issue by SamVerschueren** [editorconfig/editorconfig-vscode#24]
In the new (insiders) build, the detected indentation method (tab vs. space) and the indentation size is shown in the bottom right corner. No need for this plugin to show it anymore.

https://github.com/editorconfig/editorconfig-vscode/blob/master/src/DocumentWatcher.ts#L177-L180

<img width="420" alt="screen shot 2016-02-29 at 20 14 21" src="https://cloud.githubusercontent.com/assets/1913805/13405906/091845e8-df21-11e5-9008-42ce8ad4edc8.png">

**Comment by jedmao** [comment]
Nice!

**Comment by jedmao** [comment]
Ready to start https://code.visualstudio.com/updates/

**Comment by jedmao** [comment]
Published as v0.2.4. Thanks!

**Comment by cebor** [comment]
for me `v0.2.4` does not remove the statusbar message, it is still there.

**Comment by SamVerschueren** [comment]
You're right, still shows the statusbar message.

**Comment by jedmao** [comment]
Sorry. It looks like there was a compilation error that I didn't detect. Anyway, I just verified that version 0.2.5 indeed hides the message.

**Comment by SamVerschueren** [comment]
No problem @jedmao . Thanks for reporting @cebor !
