### ISSUE TITLE
Remove `EditorOptions` interface

### ISSUE THREAD

**Issue by SamVerschueren** [editorconfig/editorconfig-vscode#25]
The fixed `TextEditorOptions` PR was merged into the new release. So our custom options interface can be removed now.

https://github.com/editorconfig/editorconfig-vscode/blob/master/src/interfaces/editorSettings.ts

**Comment by jedmao** [comment]
Don't we have to wait for the next vscode release?

**Comment by SamVerschueren** [comment]
Yes, but just adding these so we don't forget :).

**Comment by jedmao** [comment]
Ready to start this now https://code.visualstudio.com/updates/
