### ISSUE TITLE
File not found (\.editorconfig)

### ISSUE THREAD

**Issue by ericis** [editorconfig/editorconfig-vscode#252]
- [x] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).
- [x] I tried running `code --disable-extensions` and the issue did **NOT** present itself.

Delete the following condition if it doesn't apply to your case:

If the extension is not picking up the expected configuration for a file:
- [x] I tried `npm install editorconfig -g` and ran `editorconfig [file-in-question]` and the configuration was what I expected. If not, please file on the [`editorconfig-core-js` issue tracker](https://github.com/editorconfig/editorconfig-core-js/issues).

## Issue

|             | Visual Studio Code | editorconfig-vscode |
|-------------|--------------------|---------------------|
| **Version** | `1.39.1`            | `0.14.1`             |

### Root `.editorconfig` File

On Windows 10...

* With no `C:\.editorconfig` and I get this error
* With `C:\.editorconfig`, I get the error "An .editorconfig file already exists in this workspace."

```ini
root = true

[*]
indent_style = space
indent_size = 2
```

Are there any other relevant `.editorconfig` files in your project? No

### Command run

`Generate .editorconfig` from project "Explorer".

### Expected behavior

A new `.editorconfig` file is created in the project.

### Actual behavior

An error.

* The error `File not found (\.editorconfig)` occurs when no ".editorconfig" exists anywhere on disk
* The error `An .editorconfig file already exists in this workspace.` occurs when I create a root ".editorconfig" in a parent directory

**Comment by jedmao** [comment]
Hmm, that portion of the code hasn't been touched in a while. I'll have to look into this when I'm back on my Windows machine.

Thanks for submitting the issue!

**Comment by SkyHeads** [comment]
I have the same problem to generate new editorconfig, so that it works again I installed an earlier version. fix it !!!

**Comment by jedmao** [comment]
Fixed in https://github.com/editorconfig/editorconfig-vscode/commit/f1187a31cdc89876b285b53a166c84159a365f99
