### ISSUE TITLE
Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by tjx666** [editorconfig/editorconfig-vscode#253]
- [✓ ] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).
- [ ✓] I tried running `code --disable-extensions` and the issue did **NOT** present itself.

## Issue

|                   |  os                    | Visual Studio Code | editorconfig-vscode |
|-------------|------------------|--------------------|---------------------|
| **Version**| win10pro 1909  | 1.39.2                  | 0.14.2                    |

## description
When I use the command generator .editorconfig, the plugin reports the error message as title.
![screenshot](https://user-images.githubusercontent.com/41773861/67736093-49d49e80-fa41-11e9-8cbe-40079a47aaa7.png)

**Comment by AimLuo** [comment]
我也是  
me too
