### ISSUE TITLE
Question: Is there a way to run editorconfig style across all files

### ISSUE THREAD

**Issue by deadlydog** [editorconfig/editorconfig-vscode#254]
Using an .editorconfig file in VS Code is great and works wonderfully when starting a new project. My question is around how to apply the .editorconfig styles to an existing project. I just added a .editorconfig file to an existing project in VS Code, and would like to run it against every file in the git repository to reformat/refactor them to adhere to the defined code style. Is there a way to do this?

Thanks,

**Comment by jedmao** [comment]
I suggest you run [`prettier --fix`](https://prettier.io/) on your entire code base, as [Prettier](https://prettier.io/) uses your EditorConfig configs.
