### ISSUE TITLE
Support for other properties?

### ISSUE THREAD

**Issue by Slluxx** [editorconfig/editorconfig-vscode#256]
I am trying to switch from JetBrains to VSCode but would like to keep my formatting not only because i am not working alone but also to not get git confused on modified code.

I exported my whole config as .editorconfig and put it in my projects root but noticed non of it beeing applied to my code. Its quite a huge file and the loss of my formatting is quite a dealbreaker.

**Comment by jedmao** [comment]
1. It looks like you've dodged the issue template. 😦
1. "other properties" is not specific enough.
1. It wouldn't make sense to support other properties in the vscode extension and nowhere else, so this issue makes more sense in the main editorconfig repo.

**Comment by Slluxx** [comment]
1. Whops, sorry for completly overreading the template and the tickboxes. i was at work and really stressed out because of the formatting.

2. With "other properties" i mean anything else. Not just "indent_style" or "tab_width" but anything else: where brackets in function declarations go, if there should be space inbetween brackets and the content and so on. I'll provide my example config in a few hours so you can see what i mean.

3. As IntelliJ exports everything in editorconfig format, im pretty sure it is supported by them. It just doesnt work in vscode and thats why i wrote my issue here and not the main repo.
Though as i have dodged the template, i havent tried the quick fixes you asked to do before submitting this. I will also try them later and update on this case once i am back at work, where i have my setup.

**Comment by MightyCreak** [comment]
I too would like to have more `dotnet` and `csharp` properties. It seems like the plugin currently handle the 6 properties listed in the README, with a seventh in the backlog.

To be more precise, I am talking these properties: https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2019

It would indeed be great if EditorConfig were to support these properties themselves, but the reality seems to be that each IDE needs to support some sort of _de facto_ standard made by Microsoft. I know Visual Studio 2019 does it, I think VS Code would gain a lot by supporting these properties too.

**Comment by jedmao** [comment]
EditorConfig already supports "everything else" properties, but the vscode extension only reads supported properties. For formatting, I suggest you use Prettier.
