### ISSUE TITLE
add support for end_of_line

### ISSUE THREAD

**Issue by SamVerschueren** [editorconfig/editorconfig-vscode#26]
> Would be helpful to be able to explicitly set EOL default - for example, set to LF when you're developing on Windows but know that most of your deployments will be on Linux.
> 
> Per discussion with Alex, would need to first add the relevant extension API in vscode (to change document EOL) and then add support for it in the editorconfig extension.

Original issue: https://github.com/Microsoft/vscode-editorconfig/issues/11

**Comment by SamVerschueren** [comment]
https://github.com/Microsoft/vscode/issues/3817

**Comment by SteveALee** [comment]
A described in Microsoft/vscode#11 the latest version of @code includes a setting for eol so I perhaps is now easier to implement from the extension?

Another use case is I am using [Vagrant-based CI in a Linux VM](https://github.com/GPII/qi-development-environments) and use the same VM for dev with files shared with windows HOST so can use windows tools for editing. Thus LF is best universal format.

**Comment by SamVerschueren** [comment]
This is added in the march release https://github.com/Microsoft/vscode/commit/45906d91e44bc4e62e917184933ec3e92dbacc26#diff-158dcbfd31a2238ddd6a89b8a4a23316R851.

It should be possible to do it like this.

```ts
editor.edit(edit => {
    edit.setEndOfLine(EndOfLine.LF); // EndOfLine.CRLF
});
```

Will implement this when the march release was released officially.
