### ISSUE TITLE
Single item wildcard set not applied correctly.

### ISSUE THREAD

**Issue by MicahZoltu** [editorconfig/editorconfig-vscode#261]
Please fill-in this template.

- [x] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).
- [x] I tried running `code --disable-extensions` and the issue did **NOT** present itself.

## Issue

|             | Visual Studio Code | editorconfig-vscode |
|-------------|--------------------|---------------------|
| **Version** | `1.41.0`            | `0.14.3`             |

### Root `.editorconfig` File

```ini
root = true

[*]
indent_size = 2
indent_style = space

[*.{ts}]
indent_size = 4
```

Are there any other relevant `.editorconfig` files in your project? No

| Visual Studio Code Setting     | Default | User    | Workspace |
|--------------------------------|---------|---------|-----------|
| `editor.insertSpaces`          | `true`  | `true`  | `____`    |
| `editor.tabSize`               | `4`     | `4`     | `_`       |
| `editor.trimAutoWhitespace`    | `true`  | `true`  | `____`    |
| `files.autoSave`               | `"off"` | `"off"` | `"___"`   |
| `files.insertFinalNewline`     | `false` | `false` | `_____`   |
| `files.trimTrailingWhitespace` | `false` | `false` | `_____`   |

### File opened

`./foo.ts`

### Expected behavior

```ini
indent_size = 4
```

### Actual behavior

```ini
indent_size = 2
```

### Additional comments or steps to reproduce
If I change the .editorconfig to `[*.{ts,js}]` then the TS file correctly indents with 4 spaces.  Similarly, if I change it to `[*.ts]` the TS file correctly indents with 4 spaces.  The issue appears to be if you use a wildcard set with a single item in it, it isn't matched.

**Comment by jedmao** [comment]
Pretty sure that's by design. What makes you think otherwise?

Also, this issue sounds related to the core EditorConfig features and not specifically to this extension. Please fill out the following:

---

If the extension is not picking up the expected configuration for a file:
- [ ] I tried `npm install editorconfig -g` and ran `editorconfig [file-in-question]` and the configuration was what I expected. If not, please file on the [`editorconfig-core-js` issue tracker](https://github.com/editorconfig/editorconfig-core-js/issues).

**Comment by MicahZoltu** [comment]
Ah, this just uses `editorconfig-core-js` under the hood?  You are correct that the problem appears to be there, not with this extension specifically.
```
$ npx editorconfig index.ts
indent_size=2
indent_style=space
tab_width=2
```

**Comment by MicahZoltu** [comment]
Created issue https://github.com/editorconfig/editorconfig-core-js/issues/85
