### ISSUE TITLE
Looking for new maintainer

### ISSUE THREAD

**Issue by jedmao** [editorconfig/editorconfig-vscode#263]
I can no longer contribute to or publish open source projects, so I'm looking for someone to take the reigns on maintaining and publishing new versions of this project.

Any takers?

**Comment by xuhdev** [comment]
:sob:

**Comment by jedmao** [comment]
Fortunately, most of my projects are automatically published with every merge, so there’s that. I just can’t be the one writing the PRs.

**Comment by TriMoon** [comment]
@jedmao any company that restricts participating in open source projects is best left alone and far away, because no one has the right to dictate what you can and can not do in your **FREE-TIME**...
That said pls check https://github.com/editorconfig/editorconfig-vscode/issues/265#issuecomment-593083638

@Apple pls drown if what he says is true...

**Comment by jedmao** [comment]
They must do it for liability reasons or something. I’m not jumping to any sort of judgment. That’s said, it did surprise and disappoint me.

**Comment by septatrix** [comment]
Have you tried contacting Microsoft if they would like to take ownership of this extension again or even have this extension built-in (as it is already for example in Visual Studio)?

**Comment by nrayburn-tech** [comment]
@jedmao I just wanted to check and see if you are able to still review and merge the PRs I have recently submitted.

If you can and just have been busy, then great no worries.  If not, then maybe the community can push the Microsoft issue regarding editorconfig some more to get a resolution.

**Comment by Sti2nd** [comment]
@jedmao Consider pinning this issue for greater visibility

**Comment by sourishkrout** [comment]
Hey 👋  everybody! We (@christian-bromann and I) have volunteered to take over as maintainers for this project. Might take us a bit to get into the groove. Please don't hesitate to reach out, though.

**Comment by SNDST00M** [comment]
Would be nice to mention the new maintainers over at the [Gitter](https://gitter.im/editorconfig/editorconfig-vscode)

**Comment by hickford** [comment]
Upstream Visual Studio Code feature request for EditorConfig support https://github.com/microsoft/vscode/issues/111396

Please vote for it
