### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by mobotpsmocko** [editorconfig/editorconfig-vscode#266]
- Issue Type: `Performance`
- Extension Name: `EditorConfig`
- Extension Version: `0.14.4`
- OS Version: `Windows_NT x64 6.1.7601`
- VSCode version: `1.42.1`

[EditorConfig.EditorConfig-unresponsive.cpuprofile.txt](https://github.com/editorconfig/editorconfig-vscode/files/4250834/EditorConfig.EditorConfig-unresponsive.cpuprofile.txt)

**Comment by jedmao** [comment]
The extension does file I/O every time you switch tabs or open a new file. Do you think it's any more than this? How did you notice this?

**Comment by jedmao** [comment]
Closing, as no futher information is provided.
