### ISSUE TITLE
Add link to editorconfig.org while generating .editorconfig file.

### ISSUE THREAD

**Issue by hopeless-programmer-online** [editorconfig/editorconfig-vscode#271]
As far as I understand, this extension provides a `Generate .editorconfig` button in the VSCode explorer's context menu.
If it is so, it would be **very** nice to insert the comment with a link to the [official site](https://editorconfig.org/) in the generated file. Like this:

```editorconfig
# see https://editorconfig.org/

root = true

[*]
indent_style = space
indent_size = 4
charset = utf-8
trim_trailing_whitespace = false
insert_final_newline = false
```

It might be helpful for a newcomers or unfamiliar users to spent a bit less time to google it.

**Comment by jedmao** [comment]
Or to match the front page of editorconfig.org, we could use this version:

```ini
# EditorConfig is awesome: https://EditorConfig.org
```

Accepting PRs, but please include a patch version bump and changelog.
