### ISSUE TITLE
Feature request: add ability to define default .editorconfig file content

### ISSUE THREAD

**Issue by milost1982** [editorconfig/editorconfig-vscode#277]
When I create a new project and add select "generate .editorconfig" from the extension's context menu, I always .editorconfig with the following content:

> root = true
> 
> [*]
> indent_style = space
> indent_size = 4
> charset = utf-8
> trim_trailing_whitespace = false
> insert_final_newline = false

Is there ability to define this default content? I prefer indent_size to be 2, and last to flags to be true and would like to set that as default when generating .editorconfig for a new project.

**Comment by jedmao** [comment]
No. Have you considered using snippets for that?

**Comment by jedmao** [comment]
Actually, this generate command is much smarter than that. It looks at your existing editor settings to set these defaults, so if you want it to have an `indent_size = 2` by default, then just change your editor settings to that and each new generation of `.editorconfig` will follow suit!

**Comment by jedmao** [comment]
If you don't want to auto-generate the `.editorconfig` file, I just introduced a new feature where you can specify a file path for whatever template you like. Enjoy!
