### ISSUE TITLE
Breaks git commit --verbose

### ISSUE THREAD

**Issue by daniel-liuzzi** [editorconfig/editorconfig-vscode#278]
Please fill-in this template.

- [x] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).
- [x] I tried running `code --disable-extensions` and the issue did **NOT** present itself.

## Issue

|             | Visual Studio Code | editorconfig-vscode |
|-------------|--------------------|---------------------|
| **Version** | `1.46.1`            | `v0.15.1`             |

### Root `.editorconfig` File

```ini
root = true

[*]
end_of_line = crlf
```

Are there any other relevant `.editorconfig` files in your project? **No**

| Visual Studio Code Setting     | Default | User      | Workspace |
|--------------------------------|---------|-----------|-----------|
| `editor.insertSpaces`          | `true`  | _nothing_ | _nothing_ |
| `editor.tabSize`               | `4`     | _nothing_ | _nothing_ |
| `editor.trimAutoWhitespace`    | `true`  | _nothing_ | _nothing_ |
| `files.autoSave`               | `"off"` | _nothing_ | _nothing_ |
| `files.insertFinalNewline`     | `false` | _nothing_ | _nothing_ |
| `files.trimTrailingWhitespace` | `false` | _nothing_ | _nothing_ |

### File opened

`./.git/COMMIT_EDITMSG`

### Expected behavior

`./.git/COMMIT_EDITMSG` file should be left alone (and probably everything in `./.git/`)

### Actual behavior

editorconfig-vscode formats `./.git/COMMIT_EDITMSG`, causing `git commit --verbose` to break with Windows line endings.

### Additional comments or steps to reproduce

According to the [documentation](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt--v) of `git commit --verbose`: (emphasis mine)

> **-v**  
> **--verbose**  
> Show unified diff between the HEAD commit and what would be committed at the bottom of the commit message template to help the user describe the commit by reminding what changes the commit has. Note that this diff output doesn’t have its lines prefixed with #. **This diff will not be a part of the commit message.**

Git is able to ignore the diff block thanks to a marker preceding it, which looks like this:

``` diff
# ------------------------ >8 ------------------------
# Do not touch the line above.
# Everything below will be removed.
#
```

With `end_of_line = crlf`, editorconfig-vscode alters the marker. This causes Git to not recognize it and to include the entire diff block in the commit message. Disabling the extension or even commenting out `end_of_line = crlf` restores the correct behavior. IMO,  editorconfig-vscode should exclude everything inside `./git/` from any formatting as those are Git object that are better off handled by Git itself.

**Note this is the same behavior as sindresorhus/editorconfig-sublime#55 except for Visual Studio Code instead of Sublime Text.**

**Comment by jedmao** [comment]
How is this issue specific to this extension? It looks more suitable for the EditorConfig core, as you seem to be requesting that it should ignore everything in the `.git` folder, which, BTW, you can do by placing a `.editorconfig` file directly inside your `.git` folder and inserting `root = true` into that file.

```editorconfig
root = true
```
Closing, because this is not an extension concern.

**Comment by daniel-liuzzi** [comment]
> ...which, BTW, you can do by placing a `.editorconfig` file directly inside your .git folder

I'm aware, but that might only work for just a handful repos. It wouldn't be practical for, say, several dozen; you'd have to remember to add this config, and it'd cause a lot of duplication, as the config would always be the same. Having EditorConfig not mess with `.git/` seemed like a more sensible default to me.

> It looks more suitable for the EditorConfig core

This I did not know, I'll take a look there. Thanks!

**Comment by jedmao** [comment]
I wonder if you can commit `.git/.editorconfig` to your repo.

**Comment by jedmao** [comment]
Honestly, if I were in your position, I would just add something like this to my root `.editorconfig` file:

```editorconfig
[.git/*]
end_of_line = lf
```
Or `end_of_line = unset` if that's more useful for you.
