### ISSUE TITLE
Config not applied if VS Code has file open from start

### ISSUE THREAD

**Issue by OliverJAsh** [editorconfig/editorconfig-vscode#283]
Please fill-in this template.

- [x] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).
- [x] I tried running `code --disable-extensions` and the issue did **NOT** present itself.

## Issue

|             | Visual Studio Code | editorconfig-vscode |
|-------------|--------------------|---------------------|
| **Version** | `1.47.3`            | `0.15.1`             |

### Root `.editorconfig` File

```ini
root = true

[*]
indent_size = 2
```

Are there any other relevant `.editorconfig` files in your project? No

| Visual Studio Code Setting     | Default | User    | Workspace |
|--------------------------------|---------|---------|-----------|
| `editor.insertSpaces`          | `true`  | `____`  | `____`    |
| `editor.tabSize`               | `4`     | `_`     | `_`       |
| `editor.trimAutoWhitespace`    | `true`  | `____`  | `____`    |
| `files.autoSave`               | `"off"` | `"___"` | `"___"`   |
| `files.insertFinalNewline`     | `false` | `_____` | `_____`   |
| `files.trimTrailingWhitespace` | `false` | `_____` | `_____`   |

### File opened

`main.js`:

```js
const foo = () => {
    console.log('foo')
}
```

1. Open `main.js`
2. View EditorConfig output
3. Run VS Code command "reload window" (to simulate this file being open from the time when the window is initially opened)

### Expected behavior

Settings should apply

### Actual behavior

Settings are not applied. Stuck on "initializing document watcher…"

![image](https://user-images.githubusercontent.com/921609/89398400-f9454c80-d708-11ea-8db7-951cd4a99b23.png)

### Additional comments or steps to reproduce

The settings are applied if we open the file after the window is opened, using "go to file".

**Comment by jedmao** [comment]
Hmm, this is one of those weird edge cases, it seems. This exension subscribes to the `window.onDidChangeActiveTextEditor` event and it's not getting fired on an editor reload, presumably because you didn't actually change the active text editor. There seems to be no other event to which I can subscribe that would fix this issue, so I think I'm going to the point the finger at vscode on this one for not exposing something like `onDidReloadTextEditor` or something like that.
