### ISSUE TITLE
Use workspaceContains for activationEvents

### ISSUE THREAD

**Issue by jasonwilliams** [editorconfig/editorconfig-vscode#284]
Use workspaceContains for activationEvent instead of * 

Example here:
https://code.visualstudio.com/api/references/activation-events#workspaceContains

Change would be made here:
https://github.com/editorconfig/editorconfig-vscode/blob/master/package.json#L34

Workspaces with no editorConfig won’t need to start this extension.

Should help with performance and user experience.

**Comment by jedmao** [comment]
Hi @jasonwilliams, nice to see you here!

Your request is noble, but it's undesirable, because the `.editorconfig` file may reside outside of the workspace directory or there may even be `.editorconfig` files scattered throughout the workspace folder tree.

**Comment by jasonwilliams** [comment]
The extension works on files that are not present in the workspace?

>  or there may even be .editorconfig files scattered throughout the workspace folder tree.

You can solve that with `**/` you can see the Rust extension do that here:
https://github.com/rust-analyzer/rust-analyzer/blob/master/editors/code/package.json#L66

**Comment by jedmao** [comment]
@jasonwilliams the way that EditorConfig works is that when you run it against a particular file, it looks for an adjacent `.editorconfig` file, applies any settings and continues to look for more `.editorconfig` files up the folder tree until it lands on one with `root = true` in it. As such, it's very possible that there is an `.editorconfig` file at the root of your drive (outside of your workspace).

Does `**/` include folders outside of the workspace?

**Comment by jedmao** [comment]
To be clear, the extension itself is not doing this search, but the EditorConfig JS core is, just like the other cores are doing.

**Comment by jedmao** [comment]
Also, what would be the expected behavior if your workspace had `root = true`, but you opened a file outside of your workspace? If the EditorConfig extension weren't loaded, it wouldn't run the core against the file path; thus, you would be in a bad situation of having a file open with the wrong editor settings.

**Comment by jedmao** [comment]
Sorry to spam you here, but I had one more question. Are you having actual issues with performance? The extension only runs when you change focus onto a tab or when you save a file.
