### ISSUE TITLE
The cursor will automatically move forward

### ISSUE THREAD

**Issue by 2239559319** [editorconfig/editorconfig-vscode#286]
Please fill-in this template.

- [ ] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).
- [ ] I tried running `code --disable-extensions` and the issue did **NOT** present itself.

Delete the following condition if it doesn't apply to your case:

If the extension is not picking up the expected configuration for a file:
- [ ] I tried `npm install editorconfig -g` and ran `editorconfig [file-in-question]` and the configuration was what I expected. If not, please file on the [`editorconfig-core-js` issue tracker](https://github.com/editorconfig/editorconfig-core-js/issues).

## Issue

|             | Visual Studio Code | editorconfig-vscode |
|-------------|--------------------|---------------------|
| **Version** | `x.x.x`            | `x.x.x`             |

### Root `.editorconfig` File

```ini
root = true

[*]
indent_style = space
indent_size = 2
```

Are there any other relevant `.editorconfig` files in your project? Yes / No

| Visual Studio Code Setting     | Default | User    | Workspace |
|--------------------------------|---------|---------|-----------|
| `editor.insertSpaces`          | `true`  | `____`  | `____`    |
| `editor.tabSize`               | `4`     | `_`     | `_`       |
| `editor.trimAutoWhitespace`    | `true`  | `____`  | `____`    |
| `files.autoSave`               | `"off"` | `"___"` | `"___"`   |
| `files.insertFinalNewline`     | `false` | `_____` | `_____`   |
| `files.trimTrailingWhitespace` | `false` | `_____` | `_____`   |

### File opened

`./foo.js`

### Expected behavior

```ini
indent_size = 2
```

### Actual behavior

```ini
indent_size = 4
```

**Comment by dmpe** [comment]
not a dup of https://github.com/editorconfig/editorconfig-vscode/issues/268?

**Comment by 2239559319** [comment]
> not a dup of #268?

right, and I seemed to find the problem. When I set it like below it will not cause problems.
```ini
trim_trailing_whitespace = false
```

**Comment by jedmao** [comment]
Closing, as #268 is now closed.
