### ISSUE TITLE
What is the difference between this extension and omnisharp editorconfig support?

### ISSUE THREAD

**Issue by Gryhyphen** [editorconfig/editorconfig-vscode#287]
- [x] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).

- [ ] I tried running `code --disable-extensions` and the issue did **NOT** present itself.

## Issue
This is really kinda two questions:
1. Is there a reason to download this extension now that omnisharp supports editorconfig? (https://www.strathweb.com/2019/07/editorconfig-support-in-omnisharp-and-c-extension-vs-code/)
2. Sanity check - is Omnisharp for all languages or is it only C#? If it's only C#, then I can understand why I'd still want to install this extension.

**Comment by jedmao** [comment]
It appears that Omnisharp is only for .NET.
