### ISSUE TITLE
Is not adding final new line for filename beginning with '.' eg .gitignore

### ISSUE THREAD

**Issue by SteveALee** [editorconfig/editorconfig-vscode#29]
Is this by design?

**Comment by jedmao** [comment]
@SteveALee can you confirm that you uninstalled the deprecated version and are actually using this version of the extension?

If so, what happens if you run an editorconfig core on the `.gitignore` file in your shell? Is the `insert_final_newline` setting picked up?

**Comment by SteveALee** [comment]
@jedmao Thanks. So I uninstalled and ensured to install the new one. BTW code lists the depreciated one as well which is not ideal.

Where do I find editor config core exe? I search the EditorConfig website but only see libs and extensions

**Comment by SteveALee** [comment]
Any way the problem is indeed fixed. Thanks

**Comment by SteveALee** [comment]
It was not clear I was running a depreciated version. had no way of noing.

**Comment by jedmao** [comment]
@SteveALee you may have been using a stale version of the Microsoft extension. Had you updated it, you would have been [prompted with the deprecation message](https://github.com/Microsoft/vscode-editorconfig/commit/c1becf310d70af1479938f70fb160dae5393db73).

**Comment by SteveALee** [comment]
@jedo that's getting a bit circular - I need to update to know i needed to update :-P
