### ISSUE TITLE
v0.16.3 cause cmd + z doesn't take effect sometime but the peoject no .edtorconfig file

### ISSUE THREAD

**Issue by tjx666** [editorconfig/editorconfig-vscode#299]
Please fill-in this template.

- [x] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).
- [x] I tried running `code --disable-extensions` and the issue did **NOT** present itself.

## Issue

```
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0
```

Are there any other relevant `.editorconfig` files in your project? Yes / No

No.

| Visual Studio Code Setting     | Default | User    | Workspace |
|--------------------------------|---------|---------|-----------|
| `editor.insertSpaces`          | `true`  | `____`  | `____`    |
| `editor.tabSize`               | `2`     | `_`     | `2`       |
| `editor.trimAutoWhitespace`    | `true`  | `____`  | `____`    |
| `files.autoSave`               | `"off"` | `"delay"` | `"___"`   |
| `files.insertFinalNewline`     | `false` | `_____` | `true`   |
| `files.trimTrailingWhitespace` | `false` | `_____` | `_____`   |

### Additional comments or steps to reproduce

1. open a file `test.ts`
2. type some code
3. alwaly type `cmd + z`
4. sometime `cmd + z` doesn't work, you may need type more than once

**Comment by scq** [comment]
I'm seeing this too. It looks like 0.16.2 and 0.16.3 have the issue, but 0.16.1 does not.

Have downgraded to 0.16.1 for now, via right click -> install another version in the VS code extensions panel.

**Comment by tjx666** [comment]
I have made a PR https://github.com/editorconfig/editorconfig-vscode/pull/300 to fix it.

**Comment by tjx666** [comment]
@jedmao
