### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by applevinc** [editorconfig/editorconfig-vscode#302]
- Issue Type: `Performance`
- Extension Name: `EditorConfig`
- Extension Version: `0.16.4`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.52.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\HP\AppData\Local\Temp\EditorConfig.EditorConfig-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by nrayburn-tech** [comment]
Are you still having performance issues?

**Comment by applevinc** [comment]
> Are you still having performance issues?

no

**Comment by applevinc** [comment]
closing the issue now
