### ISSUE TITLE
Add setting to specify filetype/language

### ISSUE THREAD

**Issue by kidbrax** [editorconfig/editorconfig-vscode#315]
This is a feature request. It would be cool if there was a setting to specify the filetype/language of a file. So that way, when vscode opens it, it highlights accordingly. For example, if I wanted to always have my jinja file represented as a json file, i could set this.

I know this is not standard editorconfig, so thought it fit here in the vscode extension repo.

**Comment by nrayburn-tech** [comment]
I think what you are looking for is the file associations setting in vscode.  https://code.visualstudio.com/docs/languages/identifiers

So if you have files that end in `.jinja` that you want vscode to recognize as `json`, you would configure the setting like this.
```
"files.associations": {
    "*.jinja": "json"
}
```

**Comment by kidbrax** [comment]
Yes, I actually found that right after I posted this. Thanks for the follow up.
