### ISSUE TITLE
Not working in a Godot project (GDScript)

### ISSUE THREAD

**Issue by willparsons** [editorconfig/editorconfig-vscode#324]
Please fill-in this template.

- [x] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).
- [x] I tried running `code --disable-extensions` and the issue did **NOT** present itself.

## Issue

|             | Visual Studio Code | editorconfig-vscode |
|-------------|--------------------|---------------------|
| **Version** | `1.60.0`            | `v0.16.4`             |

### Root `.editorconfig` File

```ini
root = true

indent_size = 4
indent_style = space

end_of_line = lf

trim_trailing_whitespace = true
```

Are there any other relevant `.editorconfig` files in your project? No

| Visual Studio Code Setting     | Default | User    | Workspace |
|--------------------------------|---------|---------|-----------|
| `editor.insertSpaces`          | `true`  | `____`  | `____`    |
| `editor.tabSize`               | `4`     | `_`     | `_`       |
| `editor.trimAutoWhitespace`    | `true`  | `____`  | `____`    |
| `files.autoSave`               | `"off"` | `"___"` | `"___"`   |
| `files.insertFinalNewline`     | `false` | `_____` | `_____`   |
| `files.trimTrailingWhitespace` | `false` | `_____` | `true`   |

### File opened

`./Player.gd`

### Expected behavior

```ini
indent_style = space
```

### Actual behavior

```ini
indent_style = tabs
```

**Comment by SunsetTechuila** [comment]
wrong syntax, see https://editorconfig.org/#example-file
