### ISSUE TITLE
Show warning if user has set `files.trimTrailingWhitespace` globally

### ISSUE THREAD

**Issue by SamVerschueren** [editorconfig/editorconfig-vscode#33]
If the user defined `files.trimTrailingWhitespace` as `true` in the VSCode settings, we cannot prevent trimming the whitespaces if the user set `trim_trailing_whitespace = false` in his `.editorconfig` file. That's why we should show a warning message if the global setting overrides the `.editorconfig` setting.

Possible candidates

> The currently opened folder contains workspace settings that may override EditorConfig settings.

> Workspace settings may be overriding EditorConfig settings. It is recommended that you remove the workspace settings in favor of EditorConfig.

> The currently opened file contains workspace settings that may override EditorConfig settings.

> The files.trimTrailingWhitespace workspace setting may be overriding the EditorConfig trim_trailing_whitespace setting for this file. It is recommended that you remove workspace settings that might override EditorConfig settings.

I think we should keep the message small and clear. The last one is too long and won't fit into the popup box I'm afraid. Although we can make it a little shorter and use something like this

> The files.trimTrailingWhitespace workspace setting is overriding the EditorConfig trim_trailing_whitespace setting for this file.

It's up to the user to decide what they want to do in that case.

**Comment by jedmao** [comment]
I think we can trim it down to:

> Workspace settings are overriding EditorConfig settings for this file.

We can use the same message, regardless of which setting is overriding what. I think people are smart enough to compare their workspace settings file with the EditorConfig file to detect what-all collisions there might be.

**Comment by SamVerschueren** [comment]
Not really sure about dropping the information on what setting is being overridden. Maybe something like

> The `trimTrailingWhitespace` workspace settings are overriding the EditorConfig settings for this file.

If in the future it is possible to override other EditorConfig settings, it might be hard for the user to find which setting is exactly being overridden for that file. Especially when people or working on OSS projects to do a PR and are not really familiar with how editorconfig works.

**Comment by jedmao** [comment]
We can keep the message simple now and in the future, adjust accordingly. No sense in preparing for something that may never happen. That said, your message would need to be singular:

> The `trimTrailingWhitespace` workspace setting is overriding the EditorConfig setting for this file.

**Comment by SamVerschueren** [comment]
> We can keep the message simple now and in the future, adjust accordingly. No sense in preparing for something that may never happen.

Although I agree with that, I think informing the user of what setting is being overriden is pretty crucial. Not everyone is familiar with EditorConfig and know the settings without looking in the docs. Not everyone is familiar with all the settings possible in VS Code.

> That said, your message would need to be singular

:+1:

**Comment by jedmao** [comment]
@SamVerschueren, just an FYI – [this commit](https://github.com/editorconfig/editorconfig-vscode/commit/77712dda4737ff7e4241e7e7585efb115d5c577b) fixed the build by returning a common return type.

**Comment by paulirish** [comment]
I'm seeing this message but I think my two configs actually agree....

![image](https://cloud.githubusercontent.com/assets/39191/14084012/976cad04-f4cd-11e5-9da7-fd6ed31da114.png)


Checking to see if i'm running the latest version…

**Comment by paulirish** [comment]
Appears so. I have 0.2.6 installed:
![image](https://cloud.githubusercontent.com/assets/39191/14084072/e9c62b7a-f4cd-11e5-8d4d-21f229ce38fd.png)

**Comment by SamVerschueren** [comment]
Thanks for reporting @paulirish, will fix this asap!

**Comment by paulirish** [comment]
All good! thx

**Comment by SamVerschueren** [comment]
@paulirish Can you confirm that this only happens when you try saving the user `settings.json` file?

**Comment by paulirish** [comment]
@SamVerschueren Hmmm! I coulda sworn i saw it on other files, but right now I can only repro the warning on that file..

**Comment by SamVerschueren** [comment]
@paulirish Actually it happens to all files that do not belong to your workspace and don't have a `.editorconfig` file associated with them. So as long as you edit files in the workspace or in a directory with a `.editorconfig` file, there is no problem. 

When you open a file in a directory with no `.editorconfig`, [editorconfig.parse()](https://github.com/editorconfig/editorconfig-vscode/blob/master/src/DocumentWatcher.ts#L106) returns an empty object (it should return `undefined` here in my opinion, see https://github.com/editorconfig/editorconfig-core-js/issues/36). 

Because of the empty object, [this](https://github.com/editorconfig/editorconfig-vscode/blob/master/src/transformations/trimTrailingWhitespace.ts#L26) line evaluates to `true` because `editorconfig.trim_trailing_whitespace` is `undefined`.

So, correct me if I'm wrong, the warning probably always showed up because you opened a file on your filesystem that did not have a `.editorconfig` specified.

**Comment by mafredri** [comment]
I'm experiencing the same issue with regards to configs being in agreements and seeing the warning. So I removed the line: `"files.trimTrailingWhitespace": true` from my settings. But then trailing whitespace is not being trimmed in any of my files (even though there is an `.editorconfig` file that says it should).

**Comment by SamVerschueren** [comment]
@mafredri can you create a new issue? The issue of not trimming whitespaces although it is configured in the `.editorconfig` is something different. Please include your `.editorconfig` file as well.

**Comment by sarbbottam** [comment]
>The trimTrailingWhitespace workspace or user setting is overriding the EditorConfig setting for this file.

There is no `.editorconfig` file in the directory.

![screen shot 2016-04-04 at 2 49 38 pm](https://cloud.githubusercontent.com/assets/949380/14264386/85ce99a2-fa74-11e5-9291-d37bc3f0ba7c.png)

**Comment by xuhdev** [comment]
@sarbbottam Do you have an `.editorconfig` file in an upper dir?

**Comment by sarbbottam** [comment]
Not really, the location of the file is `~/Library/Application Support/Code/User/snippets`, and there is no `.editorconfig` anywhere in that path.

**Comment by xuhdev** [comment]
Just try to confirm: do you have `~/.editorconfig`?

**Comment by sarbbottam** [comment]
<img width="366" alt="editorconfig" src="https://cloud.githubusercontent.com/assets/949380/14266005/f11a0dae-fa79-11e5-857b-988a2f447781.png">

**Comment by xuhdev** [comment]
hmm, how about

    brew install editorconfig
    editorconfig $HOME/Library/Application Support/Code/User/snippets/javascript.json

**Comment by sarbbottam** [comment]
Sorry, I don't follow you?

Why do I need to `brew install editorconfig`?

**Comment by xuhdev** [comment]
@sarbbottam Just use the command line utility to quickly check what happened. It can be an issue in the core library or in the editor plugin. By doing this, we can at least check maybe there is something there. Also, if the command outputs something, try run `find ~/Library -iname .editorconfig` .

**Comment by sarbbottam** [comment]
Is there any other way of installing `editorconfig` w/o `brew`? `brew` does not work in my system.

**Comment by xuhdev** [comment]
You can use the python version pip install editorconfig

**Comment by sarbbottam** [comment]
I get this warning when there is no `.editorconfig` but not when there is one.
Also I don't get this warning message with the [deprecated one](https://github.com/Microsoft/vscode-editorconfig).

I guess this [commit](https://github.com/editorconfig/editorconfig-vscode/commit/32f937ed2b9f3506fc6fd5a5df72cc63eecf1691) might be the cause.

**Comment by sarbbottam** [comment]
```if (editorTrimsWhitespace && !editorconfig.trim_trailing_whitespace) {```

Should there be a check for `editorconfig` first?

```if (editorTrimsWhitespace && editorconfig && !editorconfig.trim_trailing_whitespace) {```

**Comment by jedmao** [comment]
@sarbbottam, the deprecated one didn't have the warning message, because that was a newly-added feature to help people understand why, sometimes, the config isn't applied as they might expect.

As for this issue, I believe it's related to https://github.com/editorconfig/editorconfig-core-js/issues/36. I'm accepting PRs on the issue, but ever since I got a baby I haven't had much time to devote to these projects, unfortunately.

**Comment by SamVerschueren** [comment]
@sarbbottam The deprecated one lacks a lot of functionality and the community took over. As @jedmao says, the warning was recently added.

@jedmao My PR fixes that more or less but it's still a "hacky" workaround which will probably not work on every case. So I admit that it should be fixed in the `editorconfig-core`. I'll see what I can do.

**Comment by zkilgore** [comment]
Is there a way to not show the warning in the case that there is no root .editorconfig anywhere on the system, and it is only included on a project basis where necessary?

**Comment by jedmao** [comment]
@zkilgore it's not that simple, because the issue is most likely NOT due to this project, but the js core. See https://github.com/editorconfig/editorconfig-core-js/issues/36.

**Comment by Tyriar** [comment]
I'm seeing this constantly in the vscode codebase.

**.editorconfig** (no editorconfig setting)

```ini
# EditorConfig is awesome: http://EditorConfig.org

# top-most EditorConfig file
root = true

# Tab indentation
[*]
indent_style = tab
indent_size = 4

# The indent size used in the `package.json` file cannot be changed
# https://github.com/npm/npm/pull/3180#issuecomment-16336516
[{.travis.yml,npm-shrinkwrap.json,package.json}]
indent_style = space
indent_size = 2
```

**Workspace settings** (contains trimTrailingWhitespace)

```
{
	"editor.insertSpaces": false,
	"files.eol": "\n",
	"files.trimTrailingWhitespace": true,
	"files.exclude": {
		".git": true,
		"**/.DS_Store": true
	},
	"search.exclude": {
		"**/node_modules": true,
		"**/bower_components": true,
		".build/**": true,
		"out*/**": true,
		"i18n/**": true,
		"extensions/**/out/**": true
	},
	"tslint.enable": true,
	"tslint.rulesDirectory": "build/lib/tslint"
}
```

**Comment by SamVerschueren** [comment]
@Tyriar that's actually the expected behaviour in that case. The `trim_trailing_whitespace` is implicitly `false` when not defined. So this means that it should not trim the trailing whitespace. But because `files.trimTrailingWhitespace` is overriding that behaviour, the warning pops up. 

You can solve this by adding `trim_trailing_whitespace = true` under the `[*]` definition. It will still use the native built in whitespace trimmer. The benefit of this is that if someone clones the repository and does changes with for instance Sublime Text, he will also get the trim trailing whitespace feature because it is defined in the `.editorconfig` file (if he has the plugin installed off course).

**Comment by sarbbottam** [comment]
>The `trim_trailing_whitespace` is implicitly false when not defined.

Interesting, I guess, `trim_trailing_whitespace` should be true by default. Wondering what would be the use case, that someone would like to preserve the trailing white spaces?

**Comment by SamVerschueren** [comment]
> Interesting, I guess, trim_trailing_whitespace should be true by default.

Then it should become the default in every editor. You can't have different behaviour in different editors. That's why EditorConfig was created in the first place.

**Comment by sarbbottam** [comment]
>> what would be the use case, that someone would like to preserve the trailing white spaces?

Thats what I have been wondering

>Then it should become the default in every editor.

Then I would suggest, `EditorConfig` should fall back to workspace or user setting, if the corresponding rule is not defined explicitly. Or in other words, `EditorConfig` must not have any default, every rule must be explicit.

**Comment by Tyriar** [comment]
@sarbbottam I wouldn't want editorconfig to do anything without being explicitly told to, otherwise you'll get random diffs in commits from people with and without it installed. `trim_trailing_whitespace = false` is the option that does nothing.

It makes sense for the warning if and only if there is an `.editorconfig` file.

**Comment by SamVerschueren** [comment]
Me and @jedmao had a discussion on this. We decided to merge #43 . This means, if it's not defined by the `.editorconfig`, it will use the global user settings. If `.editorconfig` defines `trim_trailing_whitespace = false` and the user settings says otherwise, it will show the warning.

@Tyriar This will solve your issue.

**Comment by sarbbottam** [comment]
>This means, if it's not defined by the .editorconfig, it will use the global user settings.

@SamVerschueren I guess we both are on the same page

>>I would suggest, `EditorConfig` should fall back to workspace or user setting, if the corresponding rule is not defined explicitly. Or in other words, `EditorConfig` must not have any default, every rule must be explicit.

Am I reading it correctly?

**Comment by jedmao** [comment]
@sarbbottam that sounds right to me.

**Comment by sarbbottam** [comment]
>@jedmao closed this in #43 16 minutes ago

Thanks! 👏

**Comment by gluons** [comment]
Does it has any way to override workspace `trimTrailingWhitespace` setting with editorconfig?
Or I should use global `trim_trailing_whitespace` editorconfig setting instead of workspace setting?

**Comment by SamVerschueren** [comment]
> Or I should use global trim_trailing_whitespace editorconfig setting instead of workspace setting?

Yes. If you want to be able to turn it on/off on a per project basis.

**Comment by gluons** [comment]
@SamVerschueren OK. Thank you for your suggestion.

**Comment by dennisreimann** [comment]
Is there a way to deactivate this warning? I like to see it once, but it gets annoying pretty quickly as it comes up on every succeeding save.

**Comment by jedmao** [comment]
@dennisreimann, I'm granting your wish in #129

**Comment by dennisreimann** [comment]
@jedmao thanks! :cake:
