### ISSUE TITLE
[Feature] Add support for `curly_bracket_next_line`

### ISSUE THREAD

**Issue by scruel** [editorconfig/editorconfig-vscode#336]
Please fill-in this template.

- [x] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).

### Root `.editorconfig` File

```ini
root = true

[*]
curly_bracket_next_line = false
```

### File opened

`./main.cpp`

### Expected behavior

```cpp
int main() {
  // ...
}
```

### Actual behavior

```cpp
int main()
{
  // ...
}

**Comment by SunsetTechuila** [comment]
All property proposals belong to https://github.com/editorconfig/editorconfig. But I doubt this one will be considered, because it is not enough language-independent and general. However, it can be processed by some formatter - editorconfig spec allows custom rules
