### ISSUE TITLE
csharp_new_line_before_open_brace not working

### ISSUE THREAD

**Issue by RaymoZou** [editorconfig/editorconfig-vscode#353]
Please fill-in this template.

If the extension is not picking up the expected configuration for a file:
- [ ] I tried `npm install editorconfig -g` and ran `editorconfig [file-in-question]` and the configuration was what I expected. If not, please file on the [`editorconfig-core-js` issue tracker](https://github.com/editorconfig/editorconfig-core-js/issues).

## Issue

|             | Visual Studio Code | editorconfig-vscode |
|-------------|--------------------|---------------------|
| **Version** | `1.81.0`            | `v0.16.4`             |

### Root `.editorconfig` File

```ini
root = true

[*]
indent_style = space
indent_size = 2
```

Are there any other relevant `.editorconfig` files in your project? No

| Visual Studio Code Setting     | Default | User    | Workspace |
|--------------------------------|---------|---------|-----------|
| `editor.insertSpaces`          | `true`  | `____`  | `____`    |
| `editor.tabSize`               | `4`     | `_`     | `_`       |
| `editor.trimAutoWhitespace`    | `true`  | `____`  | `____`    |
| `files.autoSave`               | `"off"` | `"___"` | `"___"`   |
| `files.insertFinalNewline`     | `false` | `_____` | `_____`   |
| `files.trimTrailingWhitespace` | `false` | `_____` | `_____`   |

### File opened

`./foo.cs`

### Expected behavior

```ini
csharp_new_line_before_open_brace = none
```

### Actual behavior

```ini
csharp_new_line_before_open_brace = all
```

**Comment by SunsetTechuila** [comment]
@faker2048 see https://spec.editorconfig.org/#supported-pairs
