### ISSUE TITLE
EditorConfig doesn't work well in VSCode (in specific files)

### ISSUE THREAD

**Issue by lithier94675** [editorconfig/editorconfig-vscode#360]
I tried running `code --disable-extensions` and the issue did **NOT** present itself. I don't use npmjs to install EditorConfig because i don't have it.

Here are the version of VSCode and EditorConfig extension I am using.

|             | Visual Studio Code | editorconfig-vscode |
|-------------|--------------------|---------------------|
| **Version** | `1.85.1` (User)            | `0.16.4`             |

Here is the screenshot of the problem.

![image](https://github.com/editorconfig/editorconfig-vscode/assets/143094082/5bdbcbe5-f8b3-4fe9-8532-857f2fb685c5)

However, it works well in other files, like this. (I prefer tab size.)

![image](https://github.com/editorconfig/editorconfig-vscode/assets/143094082/9853b322-f2b2-448c-b02f-e001adf036f6)

### Root `.editorconfig` File

```ini
root = true

[*]
charset = utf-8
end_of_line = crlf

[*.{c, cpp, c++, cc, rc, cxx, h, hpp, h++, hh, rh, hxx, i, ii, ipp, ixx, tpp, txx, inl, fx, hlsl}]
indent_style = tab
indent_size = 4
insert_final_newline = true
trim_trailing_whitespace = true

# Formatting properties in C/C++ extension (locally)
#cpp_indent_braces = false
#cpp_new_line_before_catch = true
#cpp_new_line_before_else = true
#cpp_new_line_before_while_in_do_while = true
#cpp_space_before_comma = false
#cpp_space_after_comma = true

[*.md, mdoc, mdown, mkd, mkdoc, mdtext, mdtxt, markdown, rst]
indent_style = space
indent_size = 4
insert_final_newline = true
trim_trailing_whitespace = true

[.vscode/*.json]
indent_style = tab
indent_size = 2
insert_final_newline = true

[.github/workflows/*.{yml, yaml}]
indent_style = space
indent_size = 2
insert_final_newline = true

```

### File opened

`./include/AppWindow.h`

`./.vscode/tasks.json`

(look at the screenshots above)

### Expected behavior

```ini
[*.{c, cpp, c++, cc, rc, cxx, h, hpp, h++, hh, rh, hxx, i, ii, ipp, ixx, tpp, txx, inl, fx, hlsl}]
# It didn't change to TAB indentation
indent_style = space
indent_size = 4
insert_final_newline = true
trim_trailing_whitespace = true
```

### Actual behavior

```ini
[*.{c, cpp, c++, cc, rc, cxx, h, hpp, h++, hh, rh, hxx, i, ii, ipp, ixx, tpp, txx, inl, fx, hlsl}]
indent_style = tab
indent_size = 4
insert_final_newline = true
trim_trailing_whitespace = true
```

**Comment by lithier94675** [comment]
Looks like I found the solution:

1. Uninstall the extension and delete the `.editorconfig` file.
2. Create a new `.editorconfig` file.
3. Reinstall the extension.

Problem solved!

**Comment by Neutron3425** [comment]
What is this?

**Comment by serhiybobyr-tomtom** [comment]
It happens with some files in a project and there is no solution.
