### ISSUE TITLE
Not trimming whitespace when `trim_trailing_whitespace` is set to true

### ISSUE THREAD

**Issue by mafredri** [editorconfig/editorconfig-vscode#39]
The `trim_trailing_whitespace` does not seem to be respected in VSCode. I noticed this issue when disabling `"files.trimTrailingWhitespace"` in `settings.json` due to #33. VSCode was opened within a folder containing a `.editorconfig` file.

Here's my `.editorconfig`:
```
root = true

end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.go]
indent_style = tab

[*.sql]
indent_style = tab

[*.yml]
indent_style = space
indent_size = 2
```

**Comment by SamVerschueren** [comment]
What happens if you use this `.editorconfig`?

```ini
root = true

[*]
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.go]
indent_style = tab

[*.sql]
indent_style = tab

[*.yml]
indent_style = space
indent_size = 2
```

I don't think the `.editorconfig` is valid.

**Comment by mafredri** [comment]
doh! >_<

You're right, I was missing the `[*]`, not sure how that error ended up there. Sorry for the noise!

**Comment by SamVerschueren** [comment]
No problem :)
