### ISSUE TITLE
insert_final_newline breaks typing flow when auto-save enabled

### ISSUE THREAD

**Issue by remcoros** [editorconfig/editorconfig-vscode#40]
- I have auto-save enabled (1 sec delay).
- I have insert_final_newline = true in my editorconfig

When typing on the last line of a file, when that file is autosaved (and the newline added) it also moves the cursor position to the end of the file. Which also closes intellisense.

See this image:

![animation](https://cloud.githubusercontent.com/assets/130373/14119219/6cc652fa-f5ed-11e5-85d7-b43d5df41b2f.gif)

**Comment by jedmao** [comment]
Good catch! Willing to accept a PR if you have a fix.

**Comment by remcoros** [comment]
This might actuallly be a vscode issue.

I gave it a shot by saving the current selection before the save and applying again after the save. But vscode doesn't apply this. Anything other than the current line/char works. 

It also seems 'hacky' that a plugin needs to fiddle with cursor positions. I'll create a vscode issue for this.

**Comment by SamVerschueren** [comment]
It's possible to set the cursor position back, but you'll notice the flickering when the cursor position switches back and you'll loose the instellisense. So yes, I think it should be fixed in VS Code. If you create the issue, please link to this issue so we can easily track the progress.

**Comment by remcoros** [comment]
I tried to reset the cursor position, it works, for every position but not the original (original line count, line length). vscode just doesn't move the cursor there.

**Comment by SamVerschueren** [comment]
I think it works if you use `window.activeTextEditor.selection`

Something like this:
```js
const selection = window.activeTextEditor.selection;

window.activeTextEditor.edit(editBuilder => {
	// insert newline

	window.activeTextEditor.selection = selection;
});
```

But as stated before, you'll get the flickering.

**Comment by jedmao** [comment]
I just noticed that there's an HTML vscode setting called `html.format.endWithNewline`. I wonder if they would expose such a setting for all file types?

**Comment by jedmao** [comment]
Aha! The setting is just for formatting HTML, so it has nothing to do with auto-save. See https://github.com/Microsoft/vscode/issues/4066

See also https://github.com/SamVerschueren/vscode-final-newline/issues/9 and https://github.com/Microsoft/vscode/issues/4802

**Comment by SamVerschueren** [comment]
I recorded what it would look if you put back the cursor after the document gets saved. This is what it would look. This only happens if your cursor is at the end of the file.

![cursor-position](https://cloud.githubusercontent.com/assets/1913805/19339430/9bc2ab0e-9123-11e6-84f7-1bb6360bfbe7.gif)

**Comment by jedmao** [comment]
Looks acceptable to me. What do you think?

**Comment by jedmao** [comment]
It'll still screw up Intellisense and typing flow, as the original issue was reported.

**Comment by SamVerschueren** [comment]
Yes it only brings back the cursor/selections to the original state. Does not fix the original issue.

**Comment by jedmao** [comment]
@remcoros can you confirm that this is [fixed in v0.6.3](https://github.com/editorconfig/editorconfig-vscode/pull/130)? _Note: Intellisense may still close. Please file a separate issue for that._

**Comment by remcoros** [comment]
@jedmao The cursor sticks to its original position now. Intellisense still closes, but with a 1 sec. save delay it is acceptable. 

I'll close this

**Comment by nazimjamil** [comment]
I actually experience this issue currently when I manually save the file, I can confirm that Flow is uninterrupted if `insert_final_newline` is not present.
