### ISSUE TITLE
Add intellisense when editing .editorconfig file

### ISSUE THREAD

**Issue by SamVerschueren** [editorconfig/editorconfig-vscode#41]
I think it would be a nice addition if the editor showed suggestions while editing a `.editorconfig` file. It's just something that came to my mind of `nice to have`.

**Comment by jedmao** [comment]
Yeah. The Visual Studio extension has this capability to some extent; though, I'm not 100% sold on the implementation. Would definitely love to see a thorough implementation of possible values. For example, I'd even like to see "ignore" included as a possible value for every possible EC setting. It might help people understand how to use it in ways they haven't necessarily gleaned from the docs.
