### ISSUE TITLE
package.json missing when installed

### ISSUE THREAD

**Issue by Blackbaud-DanHamlin** [editorconfig/editorconfig-vscode#42]
I tried installing this in VS Code several times and each time the package.json is missing from ~\.vscode\extensions\EditorConfig.EditorConfig-0.2.6

I finally just created it myself and took the contents from the repo to get it working.

I have VS Code 0.10.11 on Windows 7

**Comment by jedmao** [comment]
I am unable to reproduce this issue.

**Comment by SamVerschueren** [comment]
Are you installing via the normal way? Can you install other plugins successfully? Might be an issue with vs code...

**Comment by Blackbaud-DanHamlin** [comment]
It was originally installed from the installer from visualstudio.com.  The current version was auto-update installed.  I just randomly picked another extension (PowerShell) and it installed correctly and asked me to restart vscode to enable it.

**Comment by SamVerschueren** [comment]
Have you tried removing it and reinstalling it? It looks like something went fubar in the VS Code extension installation process.

**Comment by Blackbaud-DanHamlin** [comment]
Well, that is mysterious.  I tried that several times yesterday with the same result each time.  Today it appears to be working.  Thank you for humoring me. :)

**Comment by SamVerschueren** [comment]
No problem. Good it is resolved now :)
