### ISSUE TITLE
Add details to readme about how to `ext install EditorConfig`

### ISSUE THREAD

**Issue by mikemaccana** [editorconfig/editorconfig-vscode#45]
[Microsoft's official docs only mention .vsix files](https://code.visualstudio.com/Docs/extensions/install-extension), there is no `ext` command in $PATH when Visual Studio Code is installed. How do people actually install this? Thanks.

**Comment by SamVerschueren** [comment]
Depends on the operating system but let's assume mac

### 1 Via the command palette

<kbd>cmd</kbd> + <kbd>p</kbd>

```
ext install EditorConfig
```

### 2 Via the menu

<kbd>F1</kbd>

Search for `Install Extensions` -> press <kbd>enter</kbd> -> search for `EditorConfig`

**Comment by jedmao** [comment]
I think you should hit the "Edit" button on https://code.visualstudio.com/docs/extensions/install-extension and clarify the docs. This would help people install not just this extension, but any extensions in the marketplace.

As for this project's readme, it really doesn't belong here. We could link to the docs though.
