### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by SamVerschueren** [editorconfig/editorconfig-vscode#6]
I think we should refactor the code a bit. Extract the [Utils](https://github.com/editorconfig/editorconfig-vscode/blob/master/src/editorConfigMain.ts#L306-L358) class to `Utils.ts`.

Maybe even extract each transform function (trim, final new line) to individual files. I think it would increase readability a lot and would make it easier to test separate small functions.

**Comment by jedmao** [comment]
Oh yeah. There's plenty of room for refactoring this extension and I would definitely merge that in. It's pretty difficult to read as-is.

**Comment by jedmao** [comment]
Currently, my efforts are focused on the [`TabSanity`](https://github.com/jedmao/vscode-tabsanity) extension, which is quite complimentary to this one.

**Comment by SamVerschueren** [comment]
No problem, you can assign me to this issue :).
