### ISSUE TITLE
What does it do?

### ISSUE THREAD

**Issue by jakearchibald** [editorconfig/editorconfig-vscode#65]
I've been sent a link to this saying it might be useful, but I can't find anything that says what it actually.

**Comment by SamVerschueren** [comment]
It's a plugin vor VS Code that enforces settings defined by a `.editorconfig` file. Take a look at the project website http://editorconfig.org .

**Comment by jakearchibald** [comment]
Brilliant! FWIW the vscode plugin page shows the README only (https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) and not the link to editorconfig.org - may be worth adding a link in the README?
