### ISSUE TITLE
skip .gitignored files

### ISSUE THREAD

**Issue by jdanyow** [editorconfig/editorconfig-vscode#67]
would it be possible to skip applying styles to files that are ignored via .gitignore?

**Comment by jedmao** [comment]
Please submit core feature requests at https://github.com/editorconfig/editorconfig/issues; though, I have a feeling the answer will be no. One thing you can do is add some globs to your `.editorconfig` file that match the ones in `.gitignore` and just set all the settings to `none`, `disable` or `unset` (whatever you feel makes the most sense). For example:

```ini
root = true

[*]
indent_style = space
indent_size = 4

[some-file-to-ignore.txt]
indent_style = none
indent_size = none
```

**Comment by xuhdev** [comment]
There is no direct way to do it, but the script I made [here](https://gist.github.com/xuhdev/2565b258b562270854c05f2eb813e16d) based on @jedmao 's suggestion may be helpful.
