### ISSUE TITLE
typescript autocomplete not working for new files with editorconfig

### ISSUE THREAD

**Issue by sergiomichels** [editorconfig/editorconfig-vscode#68]
For some reason the autocomplete for new typescript files is not working when I have the `.editorconfig` file in my project. When I remove it the intellisense starts working as expected.

Steps to reproduce
1. Install the editorconfig plugin
2. Open an existent typescript application and create the .editorconfig file
3. Restart vscode and create a new `.ts` file. Type "mod" and try the autocomplete, nothing happens.
4. Remove `.editorconfig` and the new file and restart the IDE.
5. Repeat step 3, it will work as expected.

The typescript output view displays as follow

```
Sending request: completions (16). Response expected: yes. Current queue length: 0
Response received: completions (16). Request took 4 ms. Success: false . Message: Error processing request. Cannot read property 'lineNumberToInfo' of undefined
```

**Comment by jedmao** [comment]
How do I open "the typescript output view"?

**Comment by sergiomichels** [comment]
The issue seems fixed in vscode 1.5.3.

@jedmao It's the output view (view > output in the menu).

**Comment by jedmao** [comment]
Ah, I thought there was somehow a different "typescript" output view. Thanks for clearing that up.

**Comment by sergiomichels** [comment]
Ops, false alarm. I still can reproduce it :(

```
[Error - 16:44:50] 'occurrences' request failed with error.
Error processing request. Cannot read property 'lineNumberToInfo' of undefined
```

**Comment by SamVerschueren** [comment]
That's odd, I don't see why our plugin messes up the VS Code internals. Have to check this when I find the time.

**Comment by sergiomichels** [comment]
Thanks @SamVerschueren

**Comment by jedmao** [comment]
@sergiomichels, I am unable to reproduce. Also, `lineNumberToInfo` occurs nowhere in this plugin, so I suspect it's another plugin that you have installed. Please, try to isolate the problem by uninstalling other plugins and confirm that it's unrelated to this plugin. Thanks.

**Comment by sergiomichels** [comment]
@jedmao OK, I will test it in an VM.

**Comment by SamVerschueren** [comment]
Since VS Code 1.7.x, you can easily disable extensions to isolate this issue.

**Comment by sergiomichels** [comment]
Thanks @SamVerschueren! With only EditorConfig extension enabled I can confirm the problem. Here's my example gif. 
![editorconfig](https://cloud.githubusercontent.com/assets/1640822/20124491/eb02f166-a60d-11e6-82e4-3b7a697c66c7.gif)

Now I'm without time, but I will try to replicate it in an simpler structure later, so you can check it in my github.

**Comment by sergiomichels** [comment]
Not sure how this was fixed, but I cannot reproduce it anymore, so closing this issue :-)
