### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by SamVerschueren** [editorconfig/editorconfig-vscode#7]
Sometimes, the build throws an error. It looks like it is failing at this line https://github.com/Microsoft/vscode-extension-vscode/blob/master/bin/install#L66

Travis: https://travis-ci.org/editorconfig/editorconfig-vscode/jobs/108735221

![screen shot 2016-02-12 at 09 39 07](https://cloud.githubusercontent.com/assets/1913805/13002141/7de8a4ca-d16c-11e5-9967-5d8530dd1f9e.png)

@bpasero any idea?

**Comment by jedmao** [comment]
I used the following instructions to get here:

## [Running tests automatically on Travis CI build machines](https://code.visualstudio.com/docs/extensions/testing-extensions#_running-tests-automatically-on-travis-ci-build-machines)

I also added the `CODE_VERSION` environment variable to Travis-CI as `0.10.6`.

**Comment by jedmao** [comment]
I think we can glean some insight from https://github.com/VSCodeVim/Vim to fix this issue.

**Comment by jedmao** [comment]
Fixed in https://github.com/editorconfig/editorconfig-vscode/pull/20

**Comment by bpasero** [comment]
I will push a fix for the error later this week and publish a new vscode module version!

**Comment by SamVerschueren** [comment]
Thanks for looking into this @bpasero :+1:
