### ISSUE TITLE
Settings aren't applied correctly after removing them

### ISSUE THREAD

**Issue by SamVerschueren** [editorconfig/editorconfig-vscode#71]
I'm not sure how this can happen and I recorded a screen capture.

![editorconfig](https://cloud.githubusercontent.com/assets/1913805/18779426/51917434-8179-11e6-8713-98a28886d9c2.gif)

The file is indented with spaces and has a tab width of 2.

At first, everything is detected like it should `Spaces: 2`. 
I change the `.editorconfig` to `tab_width = 4` and the file detects that it is 4 `Spaces: 4`.
I remove that line from the `.editorconfig` file and it should go back to `Spaces: 2`, but it still is `Spaces: 4`.

**Comment by jedmao** [comment]
Do you think this was a pre-existing issue with 0.3.1 and prior?

**Comment by jedmao** [comment]
BTW, I'm in China, so I might not be as responsive as I would normally like to be. Also, doing any amount of work on this project while in China is a PITA.

**Comment by jedmao** [comment]
Oh I think I realize why this is happening now. We only apply rules if we find a setting, but if the setting is removed, we don't find the setting; thus, don't run any code. We need to restore editor defaults for all rules for which there is no setting set. Does that make sense?

**Comment by SamVerschueren** [comment]
Not sure. I thought the config map was cleared and rebuild after a editorconfig file was changed.

**Comment by SamVerschueren** [comment]
It actually seems to be a bug in VS Code. The options being applied to the document seem to be correct. Have to dive deeper into this.

**Comment by jedmao** [comment]
@SamVerschueren, any findings?

**Comment by jedmao** [comment]
@SamVerschueren let me know if you find out anything new. This ticket is ancient, so if it were a vscode issue, it's probably gone by now.
