### ISSUE TITLE
Switch to onWillSaveTextDocument

### ISSUE THREAD

**Issue by SamVerschueren** [editorconfig/editorconfig-vscode#76]
The latest insider build has this new event called [onWillSaveTextDocument](https://github.com/Microsoft/vscode/issues/239#issuecomment-249606428). This allows us to return a `TextEdit` array which will be applied to the document.

I already made the switch in my [vscode-final-newline](https://github.com/SamVerschueren/vscode-final-newline/blob/master/extension.ts#L41-L54) plugin. Works really great and this also works with the `Save All` option, which isn't the case with the current implementation.

I will have a look when I find the time.

**Comment by jedmao** [comment]
Sounds excellent!

**Comment by SamVerschueren** [comment]
The `onWillSaveTextDocument` has more information regarding the source of the save action (e.g. autosave, manual save, etc.). Maybe we should only apply the transformations when the file is being saved manually? This might fix #58. Although not sure if that's a good strategy because people who use autosave might never press `cmd+s` themselves.
