### ISSUE TITLE
Doesn't seem to work on Mac

### ISSUE THREAD

**Issue by tysonnero** [editorconfig/editorconfig-vscode#77]
I have the EditorConfig plugin installed and my .editorconfig file in my project, however VS Code on Mac is not respecting the definitions. If I switch over to Windows in Parallels for the exact same project, VS Code uses the EditorConfig settings.

Let me know if there is any other info need to help diagnose the problems or if I'm missing some other setup on the Mac side.

**Comment by jedmao** [comment]
I don't own a Mac, so I'm afraid I can't assist in diagnosing or fixing this problem. Anyone else listening who has a Mac?

**Comment by SamVerschueren** [comment]
I'm on a mac and use this plugin every day. Are you sure it's this plugin that fails? Are the VS Code versions between Windows and macOS the same? Are the installed extensions the same?

Can you share the VS Code version and your `.editorconfig` file?

**Comment by tysonnero** [comment]
@SamVerschueren Maybe my .editorconfig file is messed up or it needs to be somewhere else in the directory structure. I feel like WebStorm and Visual Studio both respect it for this project.

```
# editorconfig.org
root = true

; 2-column tab indentation
[*.js]
indent_style = space
indent_size = 2

[*.{css,scss}]
indent_style = space
indent_size = 2

[*.md]
trim_trailing_whitespace = false
```

**Comment by SamVerschueren** [comment]
Is this valid? `; 2-column tab indentation`. Try using `#` for comments. Just guessing here... (on mobile now).

**Comment by jedmao** [comment]
@tysonnero you could also use one of the EditorConfig cores to verify that the file in question is applying the appropriate settings before assuming the editor plugin is at fault. Try this core in the CLI, since it's the same code the plugin uses for vscode: https://www.npmjs.com/package/editorconfig

**Comment by tysonnero** [comment]
@SamVerschueren I tried removing the ";" commenting (although valid) but still no luck.

@jedmao I'll give that a try. In the interim, I opened the same project in WebStorm. WebStorm honored the .editorconfig out of the box. I even modified the .editorconfig settings, and WebStorm immediately accommodated.

**Comment by tysonnero** [comment]
okay so I moved the indent_style to be global as so:

```
[*]
indent_style = space
```

That seemed to do the trick...

**Comment by tysonnero** [comment]
spoke to soon... it's actually not working even with that change...

**Comment by tysonnero** [comment]
Had a conflicting extension installed which was overriding Format Code spacing. My bad!

**Comment by joeyfigaro** [comment]
@tysonnero ...which extension was it?

**Comment by tysonnero** [comment]
@joeyfigaro sorry, I totally forget. I should of mentioned it before. I'm actually on a totally new machine now and don't even have VS Code installed...

**Comment by joeyfigaro** [comment]
@tysonnero Thanks bud. 🤘

**Comment by rizkysyazuli** [comment]
same problem. got this in .editorconfig:

```
indent_size = 2
```

and this in my VS Code user settings:

```
"editor.tabSize": 4
```

the VS Code setting won.

so, about the last comment @tysonnero

> If you're having the same issue, just try disabling them one by one to find the culprit.

did you found out specifically which plugin is the culprit?

**Comment by psrivastava** [comment]
ran into similar problem & what I've learnt is. Specifying things at Global level & then if you need to override at individual filetype level is the way to solve this issue. May it needs things to be atleast defined once at global level

**Comment by psrivastava** [comment]
@rizkysyazuli

**Comment by rizkysyazuli** [comment]
@psrivastava what do you mean by "Specifying things at Global level"? globally as in the `[*]` scope?

**Comment by psrivastava** [comment]
@rizkysyazul , thats correct. As soon as I did that, (which applied defaults for all) , then individual settings started to work

**Comment by jordydickinson** [comment]
I was having this same problem, and it turned out to be an extension called `stkb.rewrap` (<https://github.com/stkb/Rewrap>).
