### ISSUE TITLE
Using "Format Code" feature ignores editorconfig settings after updating VS Code to 1.6.0

### ISSUE THREAD

**Issue by Maximaximum** [editorconfig/editorconfig-vscode#78]
At least, the tab settings don't apply.

**Comment by jedmao** [comment]
Can you be more specific? Which setting? What does your `.editorconfig` file look like? If you use an EditorConfig CLI utility like [`editorconfig`](https://www.npmjs.com/package/editorconfig), does the file in question have the expected settings?

**Comment by qorbani** [comment]
I experience same issue! Here is my .editorconfig:

```
root = true

[*]
indent_style = space
indent_size = 4

end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
charset = utf-8

[*.md]
trim_trailing_whitespace = false

# Matches the exact files package.json and .travis.yml
[{package.json,.travis.yml}]
indent_style = space
indent_size = 2

[Makefile]
indent_style = tab
```

Here is my VSCode settings:

```
{
    "editor.fontSize": 14,
    "editor.renderWhitespace": "all",
    "editor.tabSize": 4,
    "editor.insertSpaces": true
}
```

When I open `package.json` file and use auto formating (OPTION+SHIFT+F) it correctly format based on my settings in `.editorconfig`, but then when I save the file, it fall into a loop. I think two rules fighting to override each other, one try to make it 2 space (.editorconfig) and the other one 4 space (VSCode settings)!

**Comment by SamVerschueren** [comment]
Actually that works perfectly fine here. I thought #76 was the thing causes the extension to fail, but it actually still works as expected on my system.

It might be caused by another plugin though. Care to disable all the installed plugins and only use this one? Just to make sure it's not another extension interferring with this one.

Also all the tests still pass (I know, not always accurate but still).

**Comment by SEGEEK** [comment]
I am having a similar issue, I don't know if it is the same thing though.  When I format an html file the editor config definition that says 'indent_style: space' is not respected.

I have a gif below that reproduces the issue, the leading spaces ('.') turn into tabs ('->').  I have the .editorConfig file open to the right, and you can see the status bar shows spaces:2 on the indent settings yet when I do the format it still converts to tabs.
![format-to-tab](https://cloud.githubusercontent.com/assets/3335010/19288931/fb75428e-8fcd-11e6-8b29-f3f941f8a354.gif)

**Comment by SamVerschueren** [comment]
@SEGEEK I don't think this is an issue with EditorConfig but rather with the autoformatter. Try disabling this extension and save that file again. If it still fails, it's something else. Do you have other extensions installed? If so, try disabling them all and try formatting again. And if that still fails, open an issue in the VS Code repository.

**Comment by Maximaximum** [comment]
I have to confirm that @SEGEEK's explanation is the most clear and correct. The issue seems to have nothing to do with file saving, but rather with using the "Format Code" feature.

**Comment by SamVerschueren** [comment]
The main question is, is it our extension or is it VS Code. Although less likely, it seems to me that it's a bug in VS Code as the EditorConfig settings are being applied correctly (hence the lower right corner). Don't have the time to look into it though but like I said, try without this plugin (and without any plugins) and try again.

**Comment by Maximaximum** [comment]
If I uninstall EditorConfig, the issue still applies. Another important note is that the issue seems to apply only to working with *.html files, but not *.js or *.vb files

**Comment by SamVerschueren** [comment]
Do you have an html formatter extension installed or something? If not, just file an issue in the VS Code repository.

**Comment by Maximaximum** [comment]
Disabling all other extensions chenges nothing and the issue still applies.

**Comment by Maximaximum** [comment]
Have found a relevant issue for VS Code: https://github.com/Microsoft/vscode/issues/13563

**Comment by SEGEEK** [comment]
I believe @Maximaximum is correct ... just to try it out I disabled all of my extensions and it still occurred.

I appreciate you looking into this @SamVerschueren, sorry if I took you off task with the distraction, hopefully it will help others running into the same issue.

**Comment by SamVerschueren** [comment]
Glad we figured out the cause of this. Hopefully the VS Code team will fix this asap.

**Comment by Adeynack** [comment]
In my case, I disabled the [JS-CSS-HTML-formatter](https://marketplace.visualstudio.com/items?itemName=lonefy.vscode-JS-CSS-HTML-formatter) and it started working. Hope it helps.

**Comment by Adeynack** [comment]
Well ... almost. The keyboard shortcut works, but then some config like `insert_final_newline = true` are ignored.

**Comment by baqazan** [comment]
hey guys, I experienced similar issue and I believe I found the solution - find "editor.detectIndentation" setting and set it to 'false', it will cause to apply indents from settings rather than detect it based on the file you opened. After that just go to file and use Format Code feature, it worked for me and hopefully will work for you.

**Comment by dibosh** [comment]
@Adeynack you saved my day!

**Comment by stoyaneft** [comment]
In my case the problem was caused by the **Prettier - code formatter** plugin, because it respects prettier configuration files before .editorconfig files. So if you have this plugin enabled and have a .prettierrc.json file, it will overwrite the .editorconfig settings.

In my case disabling formatOnSave for specific file types helped.
```json
"editor.formatOnSave": true,
  "[json]": {
    "editor.formatOnSave": false
  }
```

**Comment by DaveSkender** [comment]
In my case, .editorconfig was ignored because it was at the root of my repo, but not at the root of the VS Code Folder I had open.  I had assumed it would honor the "root" editor config in the repo, but it did not.

**Comment by rol-rashed** [comment]
https://stackoverflow.com/questions/37826449/expected-linebreaks-to-be-lf-but-found-crlf-linebreak-style/71268059#71268059

**Comment by rqkohistani** [comment]
https://stackoverflow.com/questions/37826449/expected-linebreaks-to-be-lf-but-found-crlf-linebreak-style/71268059#71268059

**Comment by iamwwc** [comment]
I have to disable EditorConfig.EditorConfig extention on vscode. It auto format files which cause cursor move suddenly even though `editor.formatOnSave` is false.
