### ISSUE TITLE
EditorConfig make VSCode 1.6.0 go crazy on save

### ISSUE THREAD

**Issue by maroy1986** [editorconfig/editorconfig-vscode#79]
VSCode Version: 1.6.0
OS Version: Windows 10 Build 14393.222

**Steps to Reproduce:**
Open a JSON or HTML file (might apply to more files types)
Change something
Save and look at VSCode going crazy.

**Quick video here :** 
![formatonsavefreakoutlight](https://cloud.githubusercontent.com/assets/2490360/19273748/b0c151f6-8f9b-11e6-87ea-48b53fb50045.gif)

Then, if you try to close the file, it will ask if you want to save the file, if you discard the change, sometime it will replace the whole file content with null. Haven't been able to reproduce this one, happened one time when I record the video.

There's no error in the dev console. Disabling or removing EditorConfig extension make the issue vanish.

Closed issue on VSCode repo : https://github.com/Microsoft/vscode/issues/13512

**Comment by SamVerschueren** [comment]
Do you have `formatOnSave` turned on? Turn it off and try again. This will be fixed by #76.

**Comment by maroy1986** [comment]
Yes we turn it on this morning. We turn it back off when we saw this. Sorry for the duplicate (somehow) and will wait for the release of a new version of EditorConfig to enable back the feature 👍

**Comment by SamVerschueren** [comment]
> Sorry for the duplicate 

It's not really a duplicate, thanks for reporting! :)

**Comment by piotrwitek** [comment]
critical issue, wasted a lot of time figuring which extension is giving me trouble and restoring my extensions back to normal

**Comment by jedmao** [comment]
@piotrwitek, can you confirm that this was fixed in #80, published as version 0.3.4?

**Comment by c1rus** [comment]
i had the same problem, new version seems ok.

**Comment by piotrwitek** [comment]
@jedmao 0.3.4 is working fine, no more infinite loop behavior 👍
