### ISSUE TITLE
icon not shown in marketplace

### ISSUE THREAD

**Issue by SamVerschueren** [editorconfig/editorconfig-vscode#8]
I think this

```
"icon": "./EditorConfig_icon.png"
``` 

should be replaced by 

```
"icon": "EditorConfig_icon.png"
```

in `package.json`.

**Comment by jedmao** [comment]
Yep. This worked! See https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig

**Comment by SamVerschueren** [comment]
:+1:
