### ISSUE TITLE
v0.3.4 highlights final newline after save

### ISSUE THREAD

**Issue by jedmao** [editorconfig/editorconfig-vscode#83]
## Steps to reproduce
1. Open a file for which `insert_final_newline = true`.
2. Place your cursor at the end of the file w/o a final newline.
3. Save the file.
## Expected Behavior

A final newline is inserted and the cursor moves to the end of the file.

_Note: I'm not sure what should happen with multiple cursors. Open to suggestions._
## Actual Behavior

A final newline is inserted; however, it's also highlighted. Furthermore, the cursor remains where it was before the save.

**Comment by SamVerschueren** [comment]
This is expected behavior, see #40. This makes sure that the selection is set back to what it was before the save. This this works as well with multiple cursors and multiple selections. It does break intellisense however, but that can't be solved as long as it is not supported in VS Code core.

**Comment by jedmao** [comment]
@SamVerschueren, this issue is a different one. The selection is NOT set to what it was before, because it has the final newline selected (highlighted). See the following screen capture:

![final-newline](https://cloud.githubusercontent.com/assets/1058243/19525877/0e856d0c-95e8-11e6-8ada-ce33d744d265.gif)

If my cursor is anywhere else in the file when I trigger a save then it doesn't happen, but if my cursor is already on the very last character of the file, that's when it happens.

**Comment by SamVerschueren** [comment]
Oh you're right! Thanks for elaborating. Didn't add the put back part yet. This is odd. Should we implement to put back the selections after save then?

**Comment by jedmao** [comment]
I tried to do that myself, but I wasn't having success and was running out of time so I reverted my changes. But yes, I do think we should restore the selections, if possible. The problem is that the `TextEdit[]` is not actually, itself, a `Thenable<T>`, so you can't really control the restoration of the selections unless you listen for the `onDidSaveTextDocument` event, so it gets pretty dirty. `e.waitUntil(...)` returns `void`, so you can't do a `.then()` on that either. It's frustrating.

**Comment by jedmao** [comment]
BTW, this also happens with multiple cursors, but only when one of those cursors is at the very end of the file.

**Comment by SamVerschueren** [comment]
> unless you listen for the onDidSaveTextDocument event

That's how it should be done. https://github.com/SamVerschueren/vscode-final-newline/blob/master/extension.ts#L65

**Comment by jedmao** [comment]
Fixed and published in version 0.6.2!
