### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by mrdulin** [editorconfig/editorconfig-vscode#87]
This is my `.editorconfig` file:

```js
root = true

[*]
indent_style = tab
tab_width = 4
indent_size = 4
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true
```

I install this extension. How do I use it ?
Can i use it to format my code?

**Comment by SamVerschueren** [comment]
No it does not format your code. It makes sure when creating new documents or editting documents, the settings like indentation etc. are set correctly.

**Comment by mrdulin** [comment]
@SamVerschueren oh, I thought so last night before I saw your reply. My mistake. Thanks.
