### ISSUE TITLE
Documentation to target specific file type.

### ISSUE THREAD

**Issue by rgfx** [editorconfig/editorconfig-vscode#89]
I can't find any documentation of targeting specific file types, I would like my scss and css files to use 2 space indention.  html and php can still use 4

    [*.scss]
    "editor.tabSize": 2,

Is how i think you would do it in the old editor config, but am not certain if that format works for the settings.json file.  

Please advise.

**Comment by SamVerschueren** [comment]
Where are you adding those settings? You don't have to touch `settings.json` at all. Just add a new `.editorconfig` file at the root of your project.

```ini
root = true

[*.{css,scss}]
indent_size = 2
```

**Comment by rgfx** [comment]
Ok, seeing editor inside the setting.json confused. Also have no reference to .editorconfig in the menu. 

Is there a global or default editor config? 

I like to use my setting for every project. 

Thanks.

**Comment by SamVerschueren** [comment]
I believe you can put it in the home directory, but not sure about that to be honest. Maybe @jedmao knows.

To be honest, having a global EditorConfig doesn't make sense. You could as well adjust your default editor settings yourself. EditorConfig really is used for teams to make sure everyone is working with the same settings and you don't end up with tabs and spaces in one file for example. OpenSource projects is a good example. You want contributors to adhere to your coding style (tabs, spaces, indentation size, ...). If you don't need all of that, don't bother using EditorConfig IMO.

**Comment by rgfx** [comment]
Ok, but I thought the extension beautify was pulling information from my editorconfig since it was formatting my .scss files with tabs each time I saved. 

Untill I change editor.tabSize": 2 in my setting.json

It makes sense that editorconfig is used for teams. Having it each project is a good idea in that contexts.

**Comment by jedmao** [comment]
It's unlikely that beautify is pulling your .editorconfig file, but I wouldn't rule it out. That said, you can always troubleshoot by disabling plugins that you suspect to isolate the problem down to this one or not.
