### ISSUE TITLE
insert_final_newline into editorconfig file

### ISSUE THREAD

**Issue by SamVerschueren** [editorconfig/editorconfig-vscode#9]
Original post from @glen-84

> My .editorconfig file looks like this:
> ```ini
> root = true
> 
> [*]
> charset = utf-8
> indent_style = space
> indent_size = 4
> end_of_line = lf
> trim_trailing_whitespace = true
> insert_final_newline = true
> 
> [package.json]
> indent_size = 2
> ```
> If I save it, a final newline is not added.

**Comment by SamVerschueren** [comment]
Found the reason why and also found a solution.

**Comment by jedmao** [comment]
@SamVerschueren, you rock!

**Comment by SamVerschueren** [comment]
@jedmao Thanks :) :beers:
