### ISSUE TITLE
On save of a javascript file, vscode doesn't following .editorconfig settings

### ISSUE THREAD

**Issue by zubairalam** [editorconfig/editorconfig-vscode#90]
I've tried uninstalling vim plugin and others, but it seems its vscode that is not picking .editorconfig.
How to fix this?

**Comment by SamVerschueren** [comment]
Can you share your config file?

**Comment by zubairalam** [comment]
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[Makefile]
indent_style = tab

**Comment by zubairalam** [comment]
When I save a js file vscode makes it indented by 4 spaces instead of 2 spaces.
I've tried with its inbuilt `editor.tabSize: 2`, but this also doesn't work.

**Comment by zubairalam** [comment]
I've found that `formatter` of vscode was taking priority over .editorconfig on `On Save` of a file.
Changed on save to false, and that solves the issue.
You can close this issue.
