### ISSUE TITLE
Tabs indent incorrectly overridden in Makefile

### ISSUE THREAD

**Issue by yamalight** [editorconfig/editorconfig-vscode#91]
Editing Makefile while using the `.editorconfig` file shown below currently indents everything with spaces.
Disabling editorconfig plugin make vscode correctly autodetect tabs indent.

Same config with other editors (tested in sublime and atom) works correctly.

Any ideas what might be wrong?

Test config:
```
[*]
# space indentation
indent_style = space
indent_size = 2

# tabs 2 spaces for makefiles
[Makefile]
indent_style = tabs
indent_size = 2
```

**Comment by SamVerschueren** [comment]
Try adding `root = true` at the top of the `.editorconfig` file?

**Comment by yamalight** [comment]
@SamVerschueren Just gave it a shot - same result (to be fair, it actually started with my root config that had `root = true`)

**Comment by SamVerschueren** [comment]
You made a typo, `tabs` -> `tab`.

**Comment by yamalight** [comment]
@SamVerschueren oh god. now I feel like an idiot. 😓  thanks!
wonder why it worked in other editors though 🤔 

gonna close the issue, thanks again for help!

**Comment by SamVerschueren** [comment]
No problem, those things happen :).

Maybe other editor extensions support `tab` and `tabs` which shouldn't be the case as it's not defined in the spec http://editorconfig.org/.

**Comment by yamalight** [comment]
Judging by the [source](https://github.com/sindresorhus/atom-editorconfig/blob/master/grammars/editorconfig.json#L44), it actually shouldn't have worked as well. Turns out I've used broken editorconfig for years D:
