### ISSUE TITLE
Notifying for Update Everyday？

### ISSUE THREAD

**Issue by AngusFu** [editorconfig/editorconfig-vscode#92]
I just wanna know why this plugin continued notifying users for updating？Almost everyday I launch VSCod, I would see following: 

![image](https://cloud.githubusercontent.com/assets/8180186/20604199/3311c290-b2a0-11e6-9e2d-744699b9a81f.png)

The problem is even if I had updated and reloaded, I still got another notification asking for updating.

If I could ignore the annoying blue notification  dot!

**Comment by SamVerschueren** [comment]
My best bet is that you have to upgrade/reinstall VS Code. There was a bug in previous versions of VS Code where it notified you even if the plugin was not compatible what the VS Code version. Nothing we can do about it.
