### ISSUE TITLE
quote_type support 

### ISSUE THREAD

**Issue by lcrsantos** [editorconfig/editorconfig-vscode#95]
It would be nice if this plugin could support more settings from editor config, in my case would be nice if quote type was supported.

Anyway nice job on the  plugin.

**Comment by SamVerschueren** [comment]
I don't see it listed as property http://editorconfig.org?

**Comment by lcrsantos** [comment]
I've seen it here 

https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties

but now that i look at it more carefully are just ideas for domain specific properties, it are not intended to be part of editor config but instead so that editors could rely on editor config to do so. 

i'm sorry for my distraction. 

I will now mark this as closed. thx anyway.
