### ISSUE TITLE
something wrong with my configuration?

### ISSUE THREAD

**Issue by zzzgit** [editorconfig/editorconfig-vscode#97]
```ini
root = true

[*]
end_of_line = lf
insert_final_newline = true

[*.{js,py}]
indent_style = tab
indent_size = 4
```

![image](https://cloud.githubusercontent.com/assets/1060733/22923500/b41a9e94-f2dc-11e6-8230-72bace05b6c5.png)

It indents the new line 4 tabs instead of 1 tab(which take a width of 4 spaces)
why?

**Comment by xuhdev** [comment]
Can you try to set `tab_width=4` as well?

**Comment by zzzgit** [comment]
@xuhdev  the same result as before

**Comment by SamVerschueren** [comment]
Try removing `indent_size` and add `tab_width = 4` like @xuhdev suggests. I'll have to check the docs for the correct behaviour but `indent_size` is meant for spaces, not for tabs.

**Comment by xuhdev** [comment]
`indent_size=tab` should work.

**Comment by xuhdev** [comment]
@SamVerschueren The existence of `tab_width` is for the case when people want to use both tabs and spaces for indentation. For example, if `indent_size=4` and `tab_width=8`, then the first level consist of 4 spaces and the second level should consist one tab. In any case, it seems like a bug to me after specifying `tab_width=4` while the indentation is still 4 spaces.

**Comment by zzzgit** [comment]
@SamVerschueren what you suggested did not work

**Comment by zzzgit** [comment]
what i need is:
1.use tab for indent
2.the width of the indent should be 4 spaces

**Comment by zzzgit** [comment]
it seems that maybe it's not my fault
i have try to modify this configuration for serval times,but it failed all the time
maybe it is a bug of this plugin

**Comment by SamVerschueren** [comment]
Are you using custom settings that could overwrite some of the EditorConfig settings? What do you see in the bottom right corner? It should indicate what style (`tabs` or `spaces`) it is indenting the file with and with how many characters.

**Comment by zzzgit** [comment]
![image](https://cloud.githubusercontent.com/assets/1060733/22935049/2da3881e-f30c-11e6-957d-d34187863247.png)


I got it,this one is the culprit,it conflicts with `editorconfig`
Thanks for all of you
And will you be interesting in finding out the season why they conflict with each other?

**Comment by jedmao** [comment]
What happens if you disable the EditorConfig plugin and keep `react-beautify` enabled? Are you getting the same issue? If so, it not a conflict between extensions.

**Comment by zzzgit** [comment]
nothing wrong here if i disable that plugin

**Comment by jedmao** [comment]
@zzzgit the EditorConfig plugin only ensures that the editor is configured properly. Look in your status bar for the following:

![image](https://cloud.githubusercontent.com/assets/1058243/23282778/77c4fd8c-f9e8-11e6-9dfd-264f4e202a9b.png)

If that's what you see, then EditorConfig has done its job. Anything more than that, like language-specific formatting, is outside the concern and responsibility of EditorConfig.

See also: https://github.com/editorconfig/editorconfig/issues/296#issuecomment-282126632
