### ISSUE TITLE
vscode.generateeditorconfig not found

### ISSUE THREAD

**Issue by petermbenjamin** [editorconfig/editorconfig-vscode#98]
When I type `> EditorConfig: Generate` in the command palette, I receive the following error:
> command 'vscode.generateeditorconfig' not found

![screen shot 2017-02-16 at 1 31 06 pm](https://cloud.githubusercontent.com/assets/6811830/23042188/8cbb9468-f44c-11e6-8316-a26688d22907.png)

Am I missing some configuration/setting that I need to enable in my VSCode Settings?

- I made sure I'm using the latest version of the plugin.
- I made sure I'm using the latest version of VS Code.
- I can replicate this error in a new, empty VS Code editor window.

**Comment by JimiC** [comment]
Either the extension didn't installed correctly or you are using the `vscode-oss-dev` version (self-compiled).

**Comment by jedmao** [comment]
@petermbenjamin are you still having issues?

**Comment by petermbenjamin** [comment]
@jedmao , no, the issue has been resolved by following @JimiC's suggestion.

Thank you.

**Comment by ianlini** [comment]
I'm having the same issue on kubuntu 16.04 with the latest plugin (0.7.0) and latest vscode (1.11.1). Actually, the plugin is totally not working. Any suggestion about how to debug?

**Comment by jedmao** [comment]
@ianlini you're not alone. See https://github.com/editorconfig/editorconfig-vscode/issues/135. I believe there might be some Linux-specific issues going around of recent. You can look at the EditorConfig output window to glean some information about what might be going on. I'm absolutely listening for feedback, as I'm on Windows myself.
